Loyalty feature entities
retailcrm/bitrix-module pull request #121
Opened 2020-08-19 15:11 UTC by Chazovs

2020-08-21 08:30 UTC, Neur0toxine commented on intaro.retailcrm/install/export_sale_payment/retailcrmbonus/.description.php
> +require_once($_SERVER['DOCUMENT_ROOT'] . BX_ROOT . '/modules/intaro.retailcrm/lib/component/payment/retailcrmbonus/.description.php');
Стоит сначала проверять наличие файла, т.к. если модуль удалят неправильно - это сломает CMS.

2020-08-21 08:30 UTC, Neur0toxine commented on intaro.retailcrm/install/export_sale_payment/retailcrmbonus/handler.php
> +require_once($_SERVER['DOCUMENT_ROOT'] . BX_ROOT . '/modules/intaro.retailcrm/lib/component/payment/retailcrmbonus/handler.php');
Стоит сначала проверять наличие файла, т.к. если модуль удалят неправильно - это сломает CMS.

2020-08-21 08:31 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +        foreach ($persons as $person) {
Отсутствует перевод строки.

2020-08-21 08:31 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            if (isset($groupID)) {
Отсутствует перевод строки.

2020-08-21 08:32 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            if (!$dbRes['ID']) {
Отсутствует перевод строки.

2020-08-21 08:32 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            return $result->getId();
Перед возвратом должен быть перевод строки.

2020-08-21 08:32 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +
Лишний перевод строки.

2020-08-21 08:32 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            try {
Не хватает перевода строки.

2020-08-21 08:33 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            AddMessage2Log($exception->getMessage(), $this->MODULE_ID);
Неверный отступ.

2020-08-21 08:33 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +        foreach (self::SUBSCRIBE_LP_EVENTS as $event){
Нужен перевод строки.

2020-08-21 08:33 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/payment/retailcrmbonus/handler.php
> +}
В конце файла должна быть пустая строка.

2020-08-21 08:34 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/payment/retailcrmbonus/handler.php
> +
Лишняя пустая строка.

2020-08-21 08:34 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/payment/retailcrmbonus/lang/ru/.description.php
> +$MESS["SALE_HPS_BONUS"] = "бонусный счет retailCRM";
В конце файла должна быть пустая строка.

2020-08-21 08:35 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/orderprops.php
> + * Class ToModule
Неверное имя класса в аннотации.

2020-08-21 08:35 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/orderpropsrepository.php
> + * Class RepositoryRepository
Неверное имя класса в аннотации.

2020-08-21 08:36 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/persontyperepository.php
> + * Class ToModuleRepository
Неверное имя класса в аннотации.

2020-08-21 08:36 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/orderpropsrepository.php
> + * @package  Intaro\RetailCrm\Model\Api
Неверный namespace.

2020-08-21 08:36 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/persontyperepository.php
> + * @package  Intaro\RetailCrm\Model\Api
Неверный namespace.

2020-08-21 08:36 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/tomodulerepository.php
> + * @package  Intaro\RetailCrm\Model\Api
Неверный namespace.

2020-08-21 08:37 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/annotationgenerator.php
> +<?php
Этот файл нужно удалить.

2020-08-31 10:19 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            ];
Эти переменные тоже излишни - следует перенести их в вызов метода.

2020-08-31 10:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +        return  $arResult;
Лишний пробел после `return`.

2020-08-31 10:32 UTC, Chazovs commented on intaro.retailcrm/install/index.php
> +        $saleSystemPath = COption::GetOptionString('sale', 'path2user_ps_files');
мне кажется, вынесение формирования пути в отдельную переменную, увеличивает читабельность кода.

2020-08-31 10:36 UTC, Chazovs commented on intaro.retailcrm/install/index.php
> +        $bonusProp = OrderPropsRepository::getFirstByWhere(['ID'], $where);
не согласен. нужно обсудить.

2020-08-31 10:37 UTC, Chazovs commented on intaro.retailcrm/install/index.php
> +            CSaleOrderProps::Add($fields);
тоже не согласен.

2020-08-31 10:38 UTC, Chazovs commented on intaro.retailcrm/install/index.php
> +            PaySystemActionTable::update($result->getId(), $updateData);
опять не согласен)))

2020-08-31 10:38 UTC, Chazovs commented on intaro.retailcrm/install/index.php
> +            ];
))) не согласен)))

2020-08-31 12:00 UTC, Neur0toxine requested changes

2020-09-01 06:18 UTC, Neur0toxine requested changes

2020-09-01 06:18 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            PaySystemActionTable::update($result->getId(), $updateData);
Нужен перевод строки перед вызовом метода.

2020-09-02 07:36 UTC, merged