Update RetailCrmHistory_v5.php
retailcrm/bitrix-module pull request #126
Opened 2020-08-27 11:30 UTC by DmitreyZl

Добрый день. Обнаружил недочёт в модуле. Если в заказе, явно не задан индекс, модуль пытается получить локацию из адреса доставки. Однако, если адрес передаётся строкой с разделителем "," --запятая, получить индекс и соответственно вычислить локацию из такого адреса невозможно. Т.к. в коде модуля прописан explode исключительно в случае разделителя "." -- точка. Пример такого адреса: _143006, г. Одинцово, ул. Маяковского, д. 16_ .

2020-08-28 08:23 UTC, Neur0toxine requested changes
Добрый день!

Извлечение локации усложнилось настолько, что следует в данном случае извлечь его в метод. Этот метод должен принимать параметр `$order['delivery']['address'][$key]`, и возвращать то, что устанавливается в `$parameters['filter']['PHRASE']`. Если извлечь параметр не удалось - метод должен возвращать пустую строку (т.к. это не ошибка - просто нечего извлекать). Здесь же (строка 716) следует вызывать новый метод с сохранением результата вызова в отдельную переменную. Затем нужно проверять, что в переменной не пустая строка. Если строка пустая, то следует записывать ошибку в логи так же, как это сейчас происходит. Если же строка не пустая, то её следует устанавливать в `$parameters['filter']['PHRASE']`.

2020-09-01 08:10 UTC, DmitreyZl commented
Реализовал метод извлечения локации, согласно описанной вами выше логике.

2020-09-01 12:04 UTC, DmitreyZl commented
После удаления информации о клиенте в заказе (Фамилия, отчество, имя), и выгрузке истории на сайт, полностью в битриксе затирается ФИО. Исправил данную ошибку.

2020-09-01 14:20 UTC, DmitreyZl commented
Выявил ошибку в файле RetailCrmService.php. Данный скрипт рассчитан на работу с интеграционными доставками, однако по defalt в коде  используются unsent к некоторым полям заказа. Этот код отрабатывает и при  выгрузке в CRM заказов по агенту из Битрикса. Затирается имя, фамилия, номер телефона и другие поля в информации о заказе. Ошибка выявлена в ходе работы над задачами #68249 и #68225. Смоделировал ситуацию в собственной системе и подтвердил ошибку в логике работы этого класса. Для того чтобы избежать эту ошибку, необходимо отказаться от параметров по defalt, для каждой интеграционной доставки, нужно определить поля которые нужно убрать. Реализовал это в commite и протестировал на своей системе.

2020-09-02 09:58 UTC, Neur0toxine requested changes
Необходимо также написать тесты для добавленного метода.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +    public static function orderParsLocationDelivery($adress)
Некорректный нейминг. Предлагаю использовать `parseOrderDeliveryLocation`.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +        $loc = $loc.split();
Скорее всего, этот код тут по невнимательности оказался. У строк в php ведь нет методов, а если бы и были - вызываются они не так. Нужно переписать так, чтобы этот фрагмент работал, нужно использовать `preg_replace` и `explode`.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +        }
Лишний блок else. Его содержимое вызывается если другие блоки не отработали, а значит, можно просто написать в конце метода `return [];`.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +    }
После закрытия операторной скобки должен быть перевод строки.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +    public static function orderParsLocationDelivery($adress)
В случае отсутствия PHPDoc между объявлением метода и закрывающей скобкой предыдущего метода должна быть пустая строка.

Рекомендуется добавить PHPDoc с кратким описанием того, что делает метод в summary PHPDoc.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +                                            $parameters['filter']['PHRASE'] = $loc;
Некорректно выставлены отступы.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/services/RetailCrmService.php
> +            	    unset($order['delivery']['data']);
Некорректно выставлены отступы.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/services/RetailCrmService.php
> +            	    unset($order['delivery']['data']);
Некорректно выставлены отступы.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/services/RetailCrmService.php
> +            	    unset($order['delivery']['data']);
Некорректно выставлены отступы.

2020-09-02 09:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/services/RetailCrmService.php
> +		    break;
Некорректно выставлены отступы.

2020-09-04 11:42 UTC, closed without merging