add factory class
retailcrm/bitrix-module pull request #128
Opened 2020-08-31 08:20 UTC by Chazovs

2020-09-01 07:28 UTC, Neur0toxine requested changes

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +    }
Это всё работать не будет т.к. ApiClient работает с массивами, а не с моделями.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/apiclient/clientadapter.php
> + * @method ApiResponse checkStatusPlVerification(string $string)
Нужно добавить методы с теми же именами в `ClientAdapter`. Они должны принимать модели в качестве параметров, и возвращать модели с ответом в качестве результата. Сами вызовы должны прокидываться в ApiClient, который принимает и возвращает массивы.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +
Нужно добавить phpdoc для класса.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +     * create ClientAdapter with current data for access to CRM
Между кратким описанием и тегами в аннотации лучше оставлять пустую строку - для читаемости. Само краткое описание должно быть корректным предложением, т.е. начинаться с заглавной буквы.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +        $apiKey  = Option::get('intaro.retailcrm', 'api_key');
Нужно использовать вызовы из `ConfigProvider` - для этого они и были добавлены.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +        }
Необязательный `else`. Если условие выполнится, то вернётся `null`. Если же оно не выполняется, то в любом случае должен вернуться экземпляр `ClientAdapter`.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +
Лишняя пустая строка.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +}
Не хватает перевода строки в конце файла.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +        */
Закомментированного кода в реализации не должно быть.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/request/customers/customerscorporatecompaniesrequest.php
> +po<?php
Опечатка.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +use smsverificationcreate;
Тут ведь указываются имена классов. А они регистрозависимы.
Здесь эти модели всё равно не должны быть, их нужно убрать из `ApiClient`.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationconfirm.php
> +
Стоит добавить phpdoc для namespace.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationcreate.php
> +
Стоит добавить phpdoc для namespace.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationconfirm.php
> +
Не хватает `use Intaro\RetailCrm\Component\Json\Mapping;`. Это нужно, в первую очередь, для подсказок IDE.

2020-09-01 07:28 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationcreate.php
> +
Не хватает `use Intaro\RetailCrm\Component\Json\Mapping;`. Это нужно, в первую очередь, для подсказок IDE.

2020-09-01 09:27 UTC, Chazovs commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +     * create ClientAdapter with current data for access to CRM
По поводу краткого описания (сводки): нужно оставлять две пустых строки согласно PSR-5 (хотя он еще и не принят окончательно). А вот по поводу того, что сводка должна начинаться с заглавной буквы - не согласен.  Такого требования PSR не выдвигает.

2020-09-01 09:56 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +     * create ClientAdapter with current data for access to CRM
В PSR-5 касательно блока `Summary` указано следующее:
_A Summary MUST end with two sequential line breaks, unless it is the only content in the PHPDoc._
или
_В конце сводки ДОЛЖНЫ быть два перевода строки, следующих друг за другом, но только в том случае, если кроме сводки в PHPDoc есть и другие блоки._

В моём замечании указано следующее:
_Между кратким описанием и тегами в аннотации лучше оставлять пустую строку - для читаемости._
Почему _лучше_, а не _нужно_? Потому что стандарт в статусе Draft.

Теперь перейдём к определению _перевод строки_. В Unix-like системах перевод строки - это один символ, обозначаемый кодом LF. Десятичный код символа - 10. В PHP-строках в двойных скобках обозначается сочетанием `\n`. В самом языке присутствует константа `PHP_EOL`, содержащая перевод строки для текущей системы. Согласно вышеупомянутому PSR-5, в конце блока Summary должны быть два перевода строки, т.е. для Unix-like систем там должны быть два символа LF. Приведём пример PHPDoc в виде PHP-строки:
```php
echo "/**\n * Summary block\n *\n * @return mixed\n */";
```
Если запустить этот код в REPL, то получим следующее:
```php
/**
 * Summary block
 *
 * @return mixed
 */
```
Что мы видим? Мы видим, что между блоком Summary и тегом `@return` находится *одна пустая строка* - а это именно то, что я указал в изначальном замечании. Первый перевод строки просто переводит курсор на новую строку, второй - ещё раз переводит курсор, оставляя одну пустую строку. В вышеуказанном примере между переводами строки есть ` *` - потому что пустая строка должна быть внутри блока PHPDoc.

С этим, надеюсь, всё понятно.

Теперь переходим к следующему:
_А вот по поводу того, что сводка должна начинаться с заглавной буквы - не согласен. Такого требования PSR не выдвигает._
И это вполне логично. Согласно PSR-5, в PHPDoc в Summary могут быть указаны абсолютно любые символы. Например, такой текст является валидным Summary с точки зрения PSR-5:
```
QpiniA2PfWQDDIanpy6WGS1xVYfwqyvyd6fGRvwcwaQK20V17AbNtCTuinVXvI0b9HAqQXBYpeT
```
В Summary указывается краткий комментарий. И если уж мы пишем его на английском, то нужно следовать (или стараться следовать) правилам английского языка. И синтаксис оного требует, чтобы предложения начинались с заглавной буквы, и заканчивались точкой (в большинстве случаев).

2020-09-01 09:59 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +     * create ClientAdapter with current data for access to CRM
Касательно обособления переводами строки самих блоков PHPDoc PSR-5 ничего внятного не говорит. Как правило, в коде DocBlock указывается перед документируемой сущностью, без перевода строки между блоком и сущностью. А перед DocBlock'ом ставят перевод строки (за исключением нескольких случаев, например, когда DocBlock является первым, что появляется внутри тела класса).

2020-09-01 10:41 UTC, Chazovs commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +     * create ClientAdapter with current data for access to CRM
по поводу переносов согласен. Я прочитал "два последовательными переноса строки" как две пустые строки.

2020-09-02 09:43 UTC, Neur0toxine requested changes
Заметил множество отсутствующих докблоков. При создании различных файлов PHPStorm генерирует содержимое используя шаблон, например, шаблон класса или трейта. Эти шаблоны можно отредактировать в настройках. Рекомендую это сделать добавив в шаблоны докблоки для namespace и класса. Также в общих настройках можно заставить PHPStorm автоматически добавлять в конце файла перевод строки в случае отсутствия оного.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +    }
Эти методы не так должны быть реализованы. Они должны работать исключительно с массивами, как и все остальные методы в этом клиенте. А в адаптере должны быть методы с такими же названиями, которые будут конвертировать модели в массив и вызывать методы отсюда, передавая им этот массив. Соответственно, ответы от API, получаемые в виде обёртки Response, должны быть сконвертированы адаптером в модели перед возвратом.

Лучше сделать по аналогии с существующим решением - в `Intaro\RetailCrm\Component\ApiClient\Traits` расположить `LoyaltyTrait`, в нём реализовать обёртки для методов API-клиента, и подключить трейт в адаптере.

Так нужно сделать потому что текущая версия API-клиента модели не поддерживает, и мы должны по возможности сохранять её API, чтобы можно было безболезненно обновлять клиент вручную. Также стоит учитывать, что пользователи могут использовать именно этот API-клиент в своих кастомизациях.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/factory/clientfactory.php
> +
Палец вверх стоит, а phpdoc нет. @Chazovs надо всё-таки добавить его.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/request/smsverification/smsverificationconfirmrequest.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/request/smsverification/smsverificationcreaterequest.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/request/smsverification/smsverificationstatusrequest.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/smsverification/smsverificationconfirmresponse.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/smsverification/smsverificationcreateresponse.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/smsverification/smsverificationstatusresponse.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverification.php
> +
Нужно добавить phpdoc в файл для `namespace`.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverification.php
> +
Лишний пробел.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverification.php
> +
Нужно добавить phpdoc в файл для класса.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverification.php
> +     *    Дата создания. (Y-m-d H:i:s)
Лишние пробелы в summary.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverification.php
> +     *    Дата окончания срока жизни. (Y-m-d H:i:s)
Лишние пробелы в summary.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverification.php
> +}
Не хватает перевода строки.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationconfirm.php
> +
То же, что и раньше - phpdoc отсутствует.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationconfirm.php
> +}
Не хватает перевода строки.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationconfirm.php
> +
То же, что и раньше - phpdoc отсутствует.

2020-09-02 09:43 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/smsverificationcreate.php
> +}
Не хватает перевода строки.

2020-09-02 09:43 UTC, Neur0toxine commented on tests/lib/component/factory/ClientFactoryTest.php
> +}
Не хватает перевода строки.

2020-09-02 09:43 UTC, Neur0toxine commented on tests/lib/component/factory/ClientFactoryTest.php
> +
Лишняя строка.

2020-09-02 09:43 UTC, Neur0toxine commented on tests/lib/component/factory/ClientFactoryTest.php
> +namespace Tests\Intaro\RetailCrm\Component\Factory;
Перед `namespace` должен быть перевод строки.

2020-09-03 08:58 UTC, Neur0toxine requested changes

2020-09-03 08:58 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/apiclient/clientadapter.php
> + * @method ApiResponse checkStatusPlVerification(SmsVerificationStatusRequest $request)
Эти аннотации не нужны - их стоит убрать.

2020-09-03 08:58 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +use Intaro\RetailCrm\Model\Api\Response\SmsVerification\SmsVerificationStatusResponse;
Неиспользуемые импорты нужно убрать.

2020-09-03 08:58 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/apiclient/clientadapter.php
> +use Intaro\RetailCrm\Model\Api\Response\SmsVerification\SmsVerificationStatusRequest;
Импорты моделей тут не нужны - они есть в трейте.

2020-09-03 08:58 UTC, Neur0toxine commented on tests/lib/component/factory/ClientFactoryTest.php
> +        }else{
Не хватает пробелов перед и после `else`.

2020-09-03 09:23 UTC, Neur0toxine requested changes

2020-09-03 09:23 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +
Лишний перевод строки.

2020-09-03 09:23 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/apiclient/traits/loyaltytrait.php
> +
Нужно добавить PHPDoc.

2020-09-03 09:23 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/apiclient/traits/loyaltytrait.php
> +}
Не хватает перевода строки в конце файла.

2020-09-03 09:23 UTC, Neur0toxine commented on tests/bitrixbootstrap.php
> +require_once $_SERVER['DOCUMENT_ROOT'] . '/local/tests/helpers/Helpers.php';
Не хватает перевода строки в конце файла. Также стоит не добавлять в PR то, чего по условию задачи делать не нужно.

2020-09-03 09:39 UTC, Chazovs commented on tests/lib/component/factory/ClientFactoryTest.php
> +namespace Tests\Intaro\RetailCrm\Component\Factory;
Не согласен. На сколько я понимаю, мы следуем стандарту PSR2 - в нем нет такого правила. в PSR12 есть, но мы пока им не пользуемся.

2020-09-03 10:15 UTC, Neur0toxine requested changes

2020-09-03 10:15 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/smsverification/smsverificationstatusresponse.php
> +class SmsVerificationStatusResponse extends AbstractApiModel
Эта модель ведь абсолютно идентична `SmsVerificationConfirmResponse`. Удали всё тело класса и наследуй эту модель от `SmsVerificationConfirmResponse`.

2020-09-03 10:15 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/smsverification/smsverificationcreateresponse.php
> +class SmsVerificationCreateResponse extends AbstractApiModel
Эта модель ведь абсолютно идентична `SmsVerificationConfirmResponse`. Удали всё тело класса и наследуй эту модель от `SmsVerificationConfirmResponse`.

2020-09-03 13:36 UTC, merged