add controllers and api for sms verification
retailcrm/bitrix-module pull request #138
Opened 2020-09-14 14:27 UTC by Chazovs

2020-09-14 14:46 UTC, Neur0toxine requested changes
Общие проблемы, которые нужно поправить:

1. Summary в PHPDoc либо отсутствует, либо неинформативен, либо неграмотно написан с точки зрения языка.
2. Сохраняются одни и те же ошибки с переводами строк. Рекомендую настроить IDE для добавления в конце файла переводов строк, а с остальными просто чуть более внимательно работать.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/apiclient/traits/customerscorporatetrait.php
Лишний перевод строки.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/smsverification.php
> +        $service = new UserVerificationService();
Сервис должен в конструкторе забираться из сервис-контейнера, и должен быть в сервис-контейнере зарегистрирован. Переменная со ссылкой на сервис должна иметь корректный PHPDoc чтобы работало автодополнение в IDE.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/smsverification.php
> +
Лишний перевод строки.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/dataprovider/currentuserprovider.php
> +}
Не хватает перевода строки в конце файла.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/dataprovider/currentuserprovider.php
> +     */
Тут стоит указать описание.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +    /**
Нужен перевод строки перед PHPDoc.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        $select = ['PERSONAL_PHONE'];
Лишние переменные.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        $userId = $this->user->GetID();
Переменные и вызов метода стоит разделять строкой.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        $request->verification->setLength($verificationLength);
Нужен перевод строки перед вызовом метода.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +     */
Нужно добавить описание.

2020-09-14 14:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +}
Не хватает перевода строки в конце файла.

2020-09-14 14:54 UTC, Chazovs commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        $select = ['PERSONAL_PHONE'];
Не понял, почему они лишние? Я использую их в UserRepository::getFirstByParams($where, $select);

2020-09-15 08:07 UTC, Neur0toxine requested changes
Стоит добавить хоть немного тестов в PR.

2020-09-15 08:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        $userId = $this->user->GetID();
Не в том месте стоит перевод строки.

2020-09-15 08:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        $select = ['PERSONAL_PHONE'];
Потому что напрямую можно передать. Ранее такое уже встречалось, в других PR. Не нужно создавать переменные там, где можно просто данные передать, особенно такие небольшие. Это лишняя работа для рантайма.

Читаемый код - это хорошо. Но должен быть баланс между читаемостью и эффективностью.

2020-09-15 08:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        return $this->client->checkStatusPlVerification($request);
Нужен перевод строки перед `return`.

2020-09-15 08:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +        return $this->client->confirmLpVerificationBySMS($request);
Нужен перевод строки перед `return`.

2020-09-15 08:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userverificationservice.php
> +     * @return bool
Нужно добавить Summary.

2020-09-15 10:11 UTC, Neur0toxine approved these changes

2020-09-15 10:13 UTC, Neur0toxine requested changes
Ранее аппрув некорректен; остались неисправленные замечания.

2020-09-15 10:28 UTC, Neur0toxine approved these changes

2020-09-15 11:00 UTC, merged