Lp sale arder ajax
retailcrm/bitrix-module pull request #147
Opened 2020-10-08 13:25 UTC by Chazovs

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/order_ajax.js
> +                                  }
Бонусный способ оплаты надо скрывать всегда - независимо от активности программы лояльности.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +});
Не хватает перевода строки в конце файла.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +        })
Лучше перенести вызов `.on` на строку с селектором, а переводы строки оставить в функции. Вот так:
```js
$('#bonus-input').on('keydown', function() {
        $('#bonus-msg').html('Обработка информации');
        clearInterval(intervalId);
})
```

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +    $('#bonus-input').keyup(function(){
nit: Здесь лучше заменить на `function() {` или `function () {`.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +            $('#bonus-input-error').html('Вы не можете потратить более ' + availableBonuses + ' бонусов');
При обновлении DOM никогда нельзя доверять пользовательским данным. В данном случае спасает `Number.parseInt` - если бы его не было, то благодаря этому коду в форме был бы XSS.
Здесь следует посмотреть в сторону [jQuery.text](https://api.jquery.com/text/#text).

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/lodash.js
> +/**
Не стоит импортировать всю библиотеку целиком ради одной функции. Её можно найти здесь, и скопировать напрямую: https://github.com/lodash/lodash/blob/master/debounce.js
В данном случае логично будет название файла оставить таким, как оно есть, и перенести импортируемые файлы (их всего ~3 штуки там) - конечно, CommonJS не будет в браузере работать, придётся напрямую подключить их в разметке по очереди.
В файлах должны остаться оригинальные лицензии и копирайты. Если в файле таковых нет, то в файл должен быть добавлен комментарий с указанием ссылки на оригинал (лицензия MIT позволяет так делать) .

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +    const BONUS_ERROR_MSG = 'Нельзя потратить такое количество бонусов';
Не нужно хардкодить строки сообщений. Для строк лучше использовать языковые файлы.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +                $bonusInput > 0
Первое выражение должно быть на той же строке, что и открывающая скобка условия.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +        if (ConfigProvider::getLoyaltyProgramStatus() === 'Y') {
Тело метода целиком завёрнуто в `if`. В таких случаях удобнее заменять условие на противоположное, и в теле условия выполнять возврат. Т.е.:
```php
if (false === $something) {
    return;
}

// actual business logic here
```

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +                $isBonusError                 = true;
Здесь следует возврат из функции выполнить вместо присваивания значения переменной. Саму переменную вообще нужно удалить, она не нужна т.к. если она истинна, то следующий блок вообще не выполнится.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +            && (int)$_POST['available-bonuses'] >= (int)$_POST['bonus-input']) {
Закрывающая скобка условия вместе с открывающей скобкой тела условия должны быть на отдельной строке. Также между типом, к которому кастуется переменная и самой переменной лучше оставлять пробел.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
> +    public function createSaleTemplateAction($templates, $defreplace = 'N'): array
`$defreplace` следует переименовать на что-то более понятное. Например, на `$replaceDefaultTemplate`.

2020-10-12 06:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
> +
Тут перенос строки лишний.

2020-10-12 06:58 UTC, Neur0toxine requested changes

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/templaterepository.php
> +                closedir($handle);
Не хватает переноса строки между вызовом и закрывающей операторной скобкой.

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +    function make_ajax_request() {
В названиях переменных везде camelCase, а тут snake_case. Надо и тут на camelCase изменить.

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +
Лишние пустые строки.

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    }
Идея сервиса в том, что он будет содержать бизнес-логику. А здесь просто проксируется отправка запроса.
А стоило бы реализовать логику так, чтобы в этот метод передавался идентификатор заказа в Битриксе - сервис пусть сам находит внутренний ID заказа (в запросе нет параметра с `externalId`).

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $client        = new SettingsService();
В модуле есть сервис-локатор. Сервис должен из локатора в конструкторе извлекаться, а не создаваться здесь. Работу по инициализации сервиса мы передаём локатору.

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                )->fetch();
В таком случае нужно вызовы построчно отформатировать

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +                    function(index, checkbox){
Это всё должно быть на одной строке.

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +        function replaceDefaultSaleTemplates(){
`(){` => `() {`

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +            let requestAddress = 'intaro:retailcrm.api.adminpanel.createSaleTemplate';
Здесь переменная лишняя.

2020-10-12 06:58 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    <div method="POST" action="<?php echo $uri; ?>" id="FORMACTION">
Почему `div`? При этом все параметры для формы остались.

2020-10-12 10:03 UTC, Chazovs commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +        if (ConfigProvider::getLoyaltyProgramStatus() === 'Y') {
я не могу поменять значение на противоположное, потому что у меня строгое сравнение со строкой  'Y'. Если бы там было булевое значение, то не вопрос.

2020-10-12 10:22 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    }
это увеличит нагрузку на БД: появится как минимум два лишних запроса к БД. мы и так имеем все данные в обработчике события. Нам не нужно дополнительно искать их.

2020-10-12 10:57 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/lodash.js
> +/**
не получается выделить  debouce отдельно. Сыпятся ошибки. Предлагаю, оставить как есть, либо нужно время, чтобы разобраться, как устроена эта библиотека и как из нее выделить отдельный метод.

2020-10-12 11:00 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +            $('#bonus-input-error').html('Вы не можете потратить более ' + availableBonuses + ' бонусов');
На сколько я понимаю, jQuery.text не подходит для чтения value из input

2020-10-12 13:16 UTC, Neur0toxine requested changes

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +            $('#bonus-input-error').html('Вы не можете потратить более ' + availableBonuses + ' бонусов');
Не подходит, для этого используется `.val()`. В данном случае это роли не играет т.к. `#bonus-input-error` - это `div`, и попытка вывести туда пользовательские данные без экранирования - прямой путь к XSS. В текущем коде проблемы с XSS нет, но всё равно лучше использовать `.html()` только когда в этом есть реальная необходимость.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +        if (!file_exists($lpTemplatePath)){
Между закрывающей скобкой условия и открывающей скобкой тела условия должен быть пробел.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +               return;
Нужно поправить отступы.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
> +        $newStatus = $status !== 'Y' ? 'Y' : 'N';
Тут можно указать выражение прямо в вызове после него.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
> +     * @param       $templates
Не указан тип переменной.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/loyalty/eventshandlers.php
> +     * @param                          $arResult
Почти все типы не указаны.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        return $this->client->loyaltyOrderApply($request);
Интерфейс сервиса должен выглядеть так, будто он просто работает с данными, а не с API. Т.е. здесь нужна обработка ошибок и корректные данные для возврата.

2020-10-12 13:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        return $this->client->loyaltyCalculate($request);
Интерфейс сервиса должен выглядеть так, будто он просто работает с данными, а не с API. Т.е. здесь нужна обработка ошибок и корректные данные для возврата.

2020-10-12 13:25 UTC, Chazovs commented on intaro.retailcrm/lib/controller/adminpanel.php
> +        $newStatus = $status !== 'Y' ? 'Y' : 'N';
я не хочу так делать. Это ухудшает читаемость 
Получится
ConfigProvider::setLoyaltyProgramStatus($status !== 'Y' ? 'Y' : 'N');
Выглядит, как будто матом написано.

2020-10-13 06:45 UTC, Neur0toxine requested changes

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +        }else{
Тут лучше использовать `} else {` - для читаемости.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +        setTimeout(function() {
По идее, setTimeout здесь не нужен - debounce должно хватать.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +    let intervalId;
Сюда нигде не записывается идентификатор интервала.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +        _.debounce(makeAjaxRequest, 1000));
В таком виде лучше оставить на одной строке вызов.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
>          ConfigProvider::setLoyaltyProgramStatus($newStatus);
Здесь переменная `$newStatus` не нужна. Можно ведь просто указать `ConfigProvider::setLoyaltyProgramStatus($status !== 'Y' ? 'Y' : 'N');`

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/abstractapiresponsemodel.php
> +}
Также ошибка может приходить в виде массива `errors`. В частности, при ошибке валидации ключами массива `errors` будут названия полей, а значениями будут ошибки валидации этих полей. Нужно добавить поле `errors` в эту модель.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/settings/credentialsresponse.php
> +class CredentialsResponse
Здесь тоже нужно добавить поля для ошибок (наследовать от `AbstractApiResponseModel`).

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +     * @param $bonusCount
Не указаны типы параметров.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $result = $this->client->loyaltyOrderApply($request);
Нужно либо указать какой идентификатор передаётся сюда (в данном случае достаточно переименовать `$orderId` в `$crmOrderId`, либо модифицировать метод таким образом, чтобы по переданному ID заказа в Битриксе он искал заказ в retailCRM, и брал идентификатор найденного заказа.

2020-10-13 06:45 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/abstractapiresponsemodel.php
> +}
Во всех ответах от API присутствует поле `success`, которое равно `false` в случае ошибки выполнения запроса. Нужно добавить это поле.

Также везде, где проверяется наличие ошибки, нужно проверять это поле вместо `errorMsg`. Т.е. вместо проверки вида:
```php
if (isset($result->errorMsg) && !empty($result->errorMsg)) {
    AddMessage2Log($result->errorMsg);
}
```
будет такая логика
```php
if (!$result->success) {
    if (!empty($result->errorMsg)) {
        AddMessage2Log($result->errorMsg);
    }

    if (!empty($result->errors)) {
        foreach ($errors as $key => $error) {
            AddMessage2Log(sprintf('%s: %s', $key, $error));
        }
    }
}
```
Конечно, не стоит просто копировать этот код. Его можно вынести в метод.

2020-10-13 06:46 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
>          ConfigProvider::setLoyaltyProgramStatus($newStatus);
Второй пример читается ровно так же, как и первый. Если хочется улучшить читаемость, то тогда нужно вообще убрать тернарный оператор отсюда, и использовать условие.

2020-10-13 06:47 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $result = $this->client->loyaltyOrderApply($request);
В противном случае неясно какой именно идентификатор передавать. Это ведь будет публичным API.

2020-10-13 08:13 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $result = $this->client->loyaltyOrderApply($request);
на сколько я понимаю, у нас везде используется просто номер заказа. То есть внутренний номер заказа - это и есть  номер заказа в Битриксе

2020-10-13 08:16 UTC, Chazovs commented on intaro.retailcrm/lib/model/api/response/abstractapiresponsemodel.php
> +}
$success определен в самих моделях. В какой метод нужно внести правки?

2020-10-13 08:18 UTC, Chazovs commented on intaro.retailcrm/lib/controller/adminpanel.php
>          ConfigProvider::setLoyaltyProgramStatus($newStatus);
не согласен на счет читабельности. заменил на условие.

2020-10-13 08:30 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $result = $this->client->loyaltyOrderApply($request);
Под внутренним номером заказа я имею в виду номер заказа в retailCRM. Этот номер - просто идентификатор в базе, он автоматически присваивается (да, это `id`). Конечно, этот идентификатор целочисленный. Внешний идентификатор - `externalId` - является строкой, и приходит от внешней системы. Для retailCRM номер заказа в Битриксе - это внешний идентификатор. А в передаваемом здесь запросе передаётся внутренний. Если передать в этот метод идентификатор заказа в Битриксе, то в лучшем случае получим ошибку отсутствия заказа. В худшем случае он совпадёт с каким-нибудь заказом, что приведёт к нарушению целостности данных.

2020-10-13 08:32 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/abstractapiresponsemodel.php
> +}
Нужно добавить `success` в `AbstractApiResponseModel`. В наследуемых от него моделях это поле надо будет убрать т.к. оно будет дублировать добавленное в `AbstractApiResponseModel` поле.

2020-10-13 09:41 UTC, Neur0toxine approved these changes

2020-10-13 10:04 UTC, merged