add register component
retailcrm/bitrix-module pull request #148
Opened 2020-10-13 12:03 UTC by Chazovs

2020-11-02 14:14 UTC, Neur0toxine requested changes
Те замечания, в которых предлагается добавить недостающую строку в конце файла нужно исправлять только если в конце файла нет закрывающего тега `?>`.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
> +    public function createTemplateAction(array $templates, string $donor ,$replaceDefaultTemplate = 'N'): array
Даже с учётом того, что доступ здесь лишь для администраторов, всё, что является частью пути к файлу должно фильтроваться для избежания атак с передачей пути вида `./../..`.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +        $phoneNumber = preg_replace('/\s|\+|-|\(|\)/', '', $loyaltyAccount['phone']);
Неочевидная регулярка в коде. Такое нужно выносить в отдельный метод с описанием того, что метод делает.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +
Лишний перевод строки.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +            && !empty($verificationResult->verification->verifiedAt)) {
`) {` должно быть перенесено на следующую строку.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/lang/ru/component/handlers/eventshandlers.php
> +$MESS["CAN_NOT_SAVE_ORDER"] = 'Cannot add order in retailCRM ';
Строка на английском в русском языковом файле.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/settings/credentialsresponse.php
> +     * @var \bool $success
Неймспейс для встроенного типа не нужен.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/serializedcreateloyaltyaccount.php
> +     * 	ID клиента
Лишние пробелы в описании.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/serializedentitycustomer.php
> +class SerializedEntityCustomer
Класс `IdentifiersPair` выполняет то же самое.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/logger.php
> +class Logger
Нет необходимости переносить сюда логгер. Суть появления директории `lib` была в том, чтобы появляющийся там код был написан с нуля (или почти с нуля - логика взята из старого кода, но не скопирована, а правильно реализована в новом). Перетаскивать беспорядок из старого кода в новый не стоит.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    public function checkRegInLp(): array
Большой, сложный, непонятный метод. Его надо отрефакторить.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderservice.php
> +class OrderService
То же, что и раньше. Не нужно переносить старый код в новую архитектуру. Это приведёт лишь к беспорядку.

2020-11-02 14:14 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    }else{
`} else {`

2020-11-03 07:31 UTC, Chazovs commented on intaro.retailcrm/lib/model/api/serializedentitycustomer.php
> +class SerializedEntityCustomer
удалил класс

2020-11-03 08:11 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    public function checkRegInLp(): array
отрефакторил

2020-11-03 12:49 UTC, Neur0toxine requested changes

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/result_modifier.php
> +                ['CURRENCY', '=', RetailcrmConfigProvider::getCurrencyOrDefault()],
В строке 30 используется `ConfigProvider` - здесь нужно заменить на него.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +                $service        = new LpUserAccountService();
Опять напрямую создаётся сервис. Нужен `ServiceLocator`.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +            $retailCrmEvent->orderSave($event);
Нужно добавить комментарий вида:
```
// TODO: Replace old call with a new one.
```

Если уж и вызывать старый код из нового, то нужно оставлять заметку об этом. Таких вызовов в идеале не должно быть, но если они есть - их должно быть минимальное количество.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/adminpanel.php
>                  . $template['name']
Фильтрация пути относится и к этим параметрам тоже. В том числе и ниже.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +                'msg'      => 'Некорректный номер телефона',
Для сообщений есть языковой файл.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $bonusCount = (int)$_POST['bonus-input'];
`(int) $_POST['bonus-input']`

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            && !empty($createResponse->errorMsg)) {
Закрывающая скобка условия и открывающая скобка тела условия должны находиться на новой строке.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                    }
Подобная работа с ошибками понадобится не только здесь. Это нужно выносить в отдельный метод, или в трейт / сервис.

Также требуется сохранение ключей т.к. ключами в массиве в случае ошибки валидации будут поля, которые не прошли валидацию.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            }
Очень длинные строки. Также для вывода отформатированной строки в такой ситуации лучше использовать `sprintf`.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        ) {
Это условие не должно быть многострочным.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            && $activateResponse->loyaltyAccount->active === true) {
Закрывающая скобка условия и открывающая скобка тела условия должны находиться на новой строке.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/lpuseraccountservice.php
> +    /**
Перед аннотацией нужен перевод строки.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/lpuseraccountservice.php
> +        //если в ответ получаем номер кода подтверждения, то отдаем два поля: скрытое с номером отправки и инпут для ввода кода проверки
Но ведь тут ничего не происходит. Метод пустой.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/lpuseraccountservice.php
> +    public function getExtFields($ufExtRegPlIntaro): array
Название переменной похоже на заклинание. Пусть название будет длиннее, но понятнее.

2020-11-03 12:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/lpuseraccountservice.php
> +        }
Нет проверки ошибок в ключе `errors`.

2020-11-03 12:50 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +                'msg'      => 'Некорректный номер телефона',
Все захардкоженные сообщения нужно в языковой файл вынести - не только это.

2020-11-03 14:20 UTC, Neur0toxine approved these changes

2020-11-03 14:21 UTC, Neur0toxine commented
@gwinn можно сливать.

2020-11-03 14:37 UTC, merged