Lpregistration
retailcrm/bitrix-module pull request #156
Opened 2020-11-06 13:05 UTC by Chazovs

2020-11-06 14:10 UTC, Neur0toxine approved these changes

2020-11-06 14:10 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.basket.basket/help/ru/index.php
> +<pre>
Очень странно. Файл был таким в оригинале?

2020-11-06 14:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +
Лишний перевод строки.

2020-11-06 14:11 UTC, Neur0toxine requested changes
Ошибся со статусом ревью. Вышеприведённые замечания нужно устранить.

2020-11-09 06:57 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.basket.basket/help/ru/index.php
> +<pre>
это подсказки для настроек компонента. файл таким и был. предлагаю не трогать

2020-11-09 13:05 UTC, Neur0toxine requested changes

2020-11-09 13:05 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +    public function addNewUser(Customer $customer)
Нарушен SRP. Необходимо сделать три метода: первый будет возвращать модель клиента при его наличии, второй будет создавать клиента из переданной модели, третий будет редактировать его. Затем эти методы использовать в связке там, где требуется.

Если есть необходимость вызова всех трёх методов как раньше, то следует создать метод `createOrUpdateUser`, и в нём вызывать три предыдущих метода.

2020-11-09 13:05 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/loyalty.php
> +class Loyalty
Слишком абстрактное название. Эта модель хранит данные системы лояльности для пользователя. Это значит, что имя вида `UserLoyaltyData` намного более точно описывает цель существования данной сущности.

2020-11-09 13:20 UTC, Chazovs commented on intaro.retailcrm/lib/service/userservice.php
> +    public function addNewUser(Customer $customer)
переименовал в createOrUpdateUser

2020-11-09 13:21 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +    public function addNewUser(Customer $customer)
Но нужно ведь и отрефакторить ещё. Тогда 4 метода должно получиться.

2020-11-10 07:01 UTC, Neur0toxine requested changes
https://github.com/retailcrm/bitrix-module/pull/156#discussion_r519788453 - вот эта дискуссия помечена решённой, но в действительности было лишь название метода изменено - сам метод отрефакторен не был.

2020-11-10 10:16 UTC, Neur0toxine requested changes

2020-11-10 10:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/userloyaltydata.php
> + * Class Loyalty
Нужно обновить название в Summary.

2020-11-10 10:16 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +    public function getUser(int $externalId)
Нужно переименовать в `$id`, или `$crmCustomerId`. Если же нужен поиск именно по `externalId`, то входной параметр должен быть типа `string`, и поиск, соответственно, иначе должен вестись.

2020-11-10 10:24 UTC, Neur0toxine requested changes
Три получившихся метода представляют из себя некие "прокси", которые на самом деле ничего полезного не делают, просто прокидывая данные в API-клиент. Так не должно быть.

2020-11-10 10:24 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +        return $this->client->customersGet($customersGetRequest);
Метод возвращает ответ на запрос, но не данные пользователя. Метод должен самостоятельно проверять наличие пользователя в ответе, и возвращать его только если пользователь был найден. Т.е. возвращаемым типом должен быть `\Intaro\RetailCrm\Model\Api\Customer|null`.

2020-11-10 10:24 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +        return $this->client->customersUpload($customersUploadRequest);
Метод не должен что-либо возвращать. Он должен проверять, что выгрузка прошла корректно, и выбрасывать исключение в противном случае.
Также для выгрузки одного клиента предпочтительно использовать `customerCreate`.

2020-11-10 10:24 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/userservice.php
> +        return $this->client->customersEdit($customersEditRequest);
Метод должен проверять, что редактирование произошло успешно, и выбрасывать исключение в противном случае. Метод не должен возвращать что-либо.

2020-11-10 11:42 UTC, Neur0toxine requested changes

2020-11-10 11:42 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/customerservice.php
> +        if ($response!==null && $response->success && $response->id > 0) {
Проблема с форматированием. Должно быть `$response !== null`.

2020-11-10 11:42 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/customerservice.php
> +        if ($response!==null && $response->success && $response->id > 0) {
Проблема с форматированием. Должно быть `$response !== null`.

2020-11-10 11:42 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/customerservice.php
> +        $customersGetRequest->id   = (int) $externalId;
Похоже, что проблема есть, но не здесь. В модели запроса для поля `id` нужно поменять тип на `int|string` (не забывая при этом обновить геттер и сеттер). Соответственно, здесь нужно убрать каст к `int`.

2020-11-10 11:58 UTC, Chazovs commented on intaro.retailcrm/lib/service/customerservice.php
> +        $customersGetRequest->id   = (int) $externalId;
CustomersGetRequest - DTO. Геттеров и сеттеров нет. Тип я выставил строка, так как по документации там только строка может быть

2020-11-10 12:13 UTC, Neur0toxine approved these changes

2020-11-11 06:11 UTC, Neur0toxine approved these changes

2020-11-11 08:13 UTC, merged