Lp personal
retailcrm/bitrix-module pull request #157
Opened 2020-11-13 14:44 UTC by Chazovs

2020-11-13 15:07 UTC, Neur0toxine requested changes

2020-11-13 15:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/customerservice.php
> +
Лишний перевод строки.

2020-11-13 15:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        if ($USER->IsAuthorized()) {
Не хватает перевода строки перед управляющей конструкцией.

2020-11-13 15:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $bonusCount = (int)$_POST['bonus-input'];
Между кастом и переменной нужен пробел.

2020-11-13 15:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $customerId = (string)$userId;
Между кастом и переменной нужен пробел.

2020-11-13 15:07 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    private function registerAndActivateUser(int $userId, string $userPhone, array $customFields, UserLoyaltyData $loyalty)
Слишком длинное определение функции.

2020-11-18 08:32 UTC, Neur0toxine requested changes

2020-11-18 08:32 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +    protected function fillSite(string $site, array $params): array
Это маленькое изменение полностью ломает работу модуля. Во всех методах API-клиента `$site` передаётся вторым параметром со значением `null`. Попытка вызвать любой метод без передачи `$site` теперь будет вызывать ошибку.

Необходимо либо вернуть всё как было, либо заменить тип на `?string` с заменой условия на условие вида `is_string($site) && trim($site) !== ''`, либо заменить параметр `$site` во всех методах на не-nullable тип, что ломает обратную совместимость в API-клиенте - придётся проверить весь код на предмет передачи null в любой метод клиента.

2020-11-18 08:32 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/customerservice.php
> +     * @param $userId
Не указан тип переменной.

2020-11-18 08:32 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    /**
Перед открытием DocBlock нужен перевод строки.

2020-11-18 08:32 UTC, Neur0toxine commented on snippet.php
> +<?php
Похоже, этот сниппет приходится часто использовать, верно? Стоит оформить его в полноценный cli-скрипт со справкой и параметрами, и положить в `bin/`. Тогда не придётся каждый раз его создавать и удалять.

2020-11-18 09:45 UTC, Chazovs commented on snippet.php
> +<?php
удалил

2020-11-18 09:55 UTC, Neur0toxine approved these changes

2020-11-23 12:19 UTC, merged