Sms verification reg
retailcrm/bitrix-module pull request #162
Opened 2020-11-27 11:58 UTC by Chazovs

2020-11-30 10:10 UTC, Neur0toxine requested changes

2020-11-30 10:10 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.basket.basket/templates/.default/lang/ru/template.php
> +$MESS["BONUSES_TOTAL"] = "Будет начислено бонусов (не менее)";
Т.е. число бонусов для начисления неточное? Представим со стороны клиента такую ситуацию. Идёт он оформлять заказ, а там написано "будет начислено бонусов не менее". Это как? Могут больше начислить? А сколько? А если не больше? А как больше бонусов могут начислить, как такое получить? Непонятно.

Тут нужно либо разобраться почему неточное число, и уже из API должно возвращаться точно, либо добавить пояснительную надпись (хотя бы иконку вопроса со всплывашкой). Иначе непонятно чего ждать от бонусной системы.

2020-11-30 10:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +        return $service->tryActivate((int) $idInLoyalty);
Нужно сначала проверять, что в аргументе действительно число, а потом уже вызывать сервис. Для аргумента, не проходящего проверку необходимо отдавать корректное сообщение об ошибке.

2020-11-30 10:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +use function Sodium\add;
Вероятно, было добавлено PHPStorm'ом и пропущено.

2020-11-30 10:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2020-11-30 10:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        }catch (SystemException $exception){
`} catch`

2020-11-30 10:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                && $expiredTime->format('Y-m-d H:i:s') > $nowTime->format('Y-m-d H:i:s')
Не нужно форматировать даты здесь. PHP умеет сравнивать объекты дат напрямую.

2020-11-30 10:11 UTC, Neur0toxine requested changes

2020-11-30 10:11 UTC, Neur0toxine commented on intaro.retailcrm/install/export/bitrix/js/intaro/sms.js
> +            console.log(response);
Явно отладочный вызов. Нужно убрать.

2020-12-07 08:43 UTC, Chazovs commented on intaro.retailcrm/install/export/bitrix/js/intaro/sms.js
> +    function updateClock() {
я не могу так сделать, потому что тогда возникнет дублирование кода (updateClock вызывается два раза в этом методе)

2020-12-07 10:22 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.basket.basket/templates/.default/lang/ru/template.php
> +$MESS["BONUSES_TOTAL"] = "Будет начислено бонусов (не менее)";
да, число бонусов неточное. Количество начисляемых бонусов зависит от количества бонусов, которые будут тратить.  Пока так.

2020-12-07 14:14 UTC, Neur0toxine requested changes

2020-12-07 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/lang/ru/controller/loyalty/register.php
> +$MESS["ARGUMENT_ERROR"]                = 'Ошибка активации аккаунта в программе лояльности ($idInLoyalty должно быть строкой, содержащий число).';
Из API не должны возвращаться ошибки, демонстрирующие внутренности реализации. Название переменной лучше убрать заменив на описание того, что это за данные.

2020-12-07 14:14 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +            return ['msg' => GetMessage('ARGUMENT_ERROR')];
Здесь от API возвращается сообщение об ошибке и 200-я. Неправильно использовать такой формат для ошибок.
Предлагаю использовать следующий формат:
- Возвращаем код 400.
- В ответе JSON-объект с полями `errors` и `errorCode`. `errors` представляет из себя массив строк с текстом ошибок. Если ошибка одна, то и массив содержит одну строку.
- Поле `errorCode` содержит текстовый код ошибки. Например, `generic_error` или `validation_error`.

2020-12-08 09:01 UTC, Chazovs commented on intaro.retailcrm/install/export/bitrix/js/intaro/sms.js
> +        });
Битрикс возвращает 200 статус даже в случае наличия ошибки. Предлагаю эту правку включить в отдельную задачу.

2020-12-08 09:02 UTC, Chazovs commented on intaro.retailcrm/lib/controller/loyalty/register.php
> +            return ['msg' => GetMessage('ARGUMENT_ERROR')];
Эту правку вынесем в отдельную задачу.

2020-12-08 14:10 UTC, Neur0toxine requested changes
Касательно обработки ошибок не создавал дискуссии т.к. будем отдельно заниматься этим.

2020-12-08 14:10 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/utils.php
> +    }
Этот метод удаляет плюс, пробелы и скобки из строки. Он не выполняет валидацию - он модифицирует входные данные. Нужно поменять либо логику работы метода, либо его название.

2020-12-16 12:47 UTC, closed without merging