Sms verification order
retailcrm/bitrix-module pull request #167
Opened 2020-12-14 15:57 UTC by Chazovs

2020-12-15 10:17 UTC, Neur0toxine requested changes

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        ) {
Неверно отформатировано условие.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $customerId = (string)$userId;
Между кастом и переменной должен быть пробел.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        return (int)$bonusPayment->getField('SUM') / $rate;
Между кастом и переменной нужен пробел.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    public function getBonusPayment($orderId){
Открывающая скобка тела метода должна быть на новой строке.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            }
После этой строки желательно добавить перевод строки.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2020-12-15 10:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/utils.php
> +    public static function phoneValidate(string $phoneNumber)
Нужно переименовать метод т.к. он не валидирует телефон, а убирает лишние символы из него.

2020-12-15 10:36 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/confirm.php
> +                                            $orderAccountNumber   = urlencode(urlencode($arResult["ORDER"]["ACCOUNT_NUMBER"]));
так было у битрикса. предлагаю не трогать.

2020-12-15 11:14 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $customerId = (string)$userId;
PSR-12 не предъявляет такого требования. Пробел можно не ставить.

2020-12-15 11:14 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        return (int)$bonusPayment->getField('SUM') / $rate;
PSR-12 не предъявляет такого требования. Пробел можно не ставить.

2020-12-15 11:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        return (int)$bonusPayment->getField('SUM') / $rate;
PSR-12 не требует добавлять перевод строки после управляющих структур если после них присутствует какой-либо код. Однако, мы добавляем этот перевод строки для читаемости.

Тут ситуация аналогичная.

2020-12-15 11:20 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $customerId = (string)$userId;
См. https://github.com/retailcrm/bitrix-module/pull/167#discussion_r543259142

2020-12-15 11:36 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/confirm.php
> +    if ($arResult['LOYALTY_STATUS'] === 'Y' && $arResult['PERSONAL_LOYALTY_STATUS'] === true) {
Дело в том, что LOYALTY_STATUS мы получаем из колонки value таблицы b_option через ConfigProvider. Value - колонка типа text. провайдер возвращает ее значение. А PERSONAL_LOYALTY_STATUS мы получаем через LoyaltyService::getLoyaltyPersonalStatus(), который возвращает булевое значение, в зависимости о соответствия значения в таблице b_uts_user в поле UF_EXT_REG_PL_INTARO '1', которое хоть и является int, но через модель пользователя CUser возвращается строкой.

2020-12-16 12:39 UTC, Neur0toxine requested changes

2020-12-16 12:39 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            && $smsCookie->resendAvailable > $nowTime) {
Неправильно отформатировано условие.

2020-12-16 12:39 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                $smsCookie->isVerified      = $cookieArray['isVerified'];
Почему бы не задействовать здесь десериалайзер?

2020-12-16 12:39 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            ]),
Здесь можно задействовать сериалайзер.

2020-12-16 14:21 UTC, Neur0toxine requested changes

2020-12-16 14:21 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2020-12-16 14:21 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                return Deserializer::deserialize($cookieArray,SmsCookie::class);
Между запятой и следующим аргументом должен быть пробел.

2020-12-16 14:21 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                return Deserializer::deserialize($cookieArray,SmsCookie::class);
Вижу, что код не проверялся на работоспособность. Потому что он не будет работать: первый аргумент метода `Deserializer::deserialize` - это строка с JSON. Вызов `json_decode` здесь не нужен.

Также нужно проверить, что всё работает корректно после внесения изменений.

2020-12-16 14:21 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            json_encode($serializedArray),
Здесь можно вызывать метод `Serializer::serialize`, который вернёт строку с JSON.

2020-12-18 08:31 UTC, Neur0toxine approved these changes

2020-12-18 09:03 UTC, merged