add hl during the installation process
retailcrm/bitrix-module pull request #174
Opened 2021-01-13 08:31 UTC by Chazovs

2021-01-13 13:03 UTC, Neur0toxine requested changes

2021-01-13 13:03 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/loyaltyhlblock.php
> +class LoyaltyHlBlock
В названии идёт упор на highload-блок, но совершенно непонятно что за данные хранит сущность. Предлагаю изменить название на что-то вроде `OrderLoyaltyData`, с изменением названий связанных классов (репозитория, сервиса), и их методов.

2021-01-13 13:03 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hlblockservice.php
> +            foreach ($arLangs as $langKey => $langVal) {
Перед циклом желательно добавить перевод строки.

2021-01-13 13:03 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hlblockservice.php
> +            foreach ($errors as $error){
Можно сократить как `foreach ($result->getErrorMessages() as $error) { ... }`. Перед открывающей скобкой тела цикла должен быть пробел.

2021-01-13 13:03 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hlblockservice.php
> +
Лишняя пустая строка.

2021-01-13 13:03 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hlblockservice.php
> +
В данном случае можно опустить пустую строку - на читаемость не повлияет. При инициализации нового объекта всё же стоит указывать скобки.

2021-01-13 13:39 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/lp.register/templates/.default/script.js
> +//переименовать в saveUserLpFields
указал маркер.

2021-01-13 13:39 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/lp.register/templates/.default/script.js
> +//TODO проверить - возможно, это мертвый метод
исправление TODO предлагаю вынести в отдельную задачу.

2021-01-13 13:46 UTC, Chazovs commented on intaro.retailcrm/lib/model/bitrix/loyaltyhlblock.php
> +class LoyaltyHlBlock
не соглашусь. С данными заказа у нас во многом работает LoyaltyService (в котором, в частности, есть такие методы как applyBonusesInOrder или sendBonusPayment). hlblockservice.php работает именно с HL блоком, а не со всей информацией о программе лояльности, которая у нас есть в заказе. К заказу будут привязаны кастомные поля плательщиков, скидки (возможно), покупатели с их кастомными полями. HL - это лишь часть информации. Мне кажется логичным оставить именно такое название.

2021-01-14 07:35 UTC, Chazovs commented on intaro.retailcrm/options.php
> +use \Intaro\RetailCrm\Service\Utils as Utilyty;
просто есть класс \Utils. Если я буду использовать без псевдонима, то будет неоднозначность.

2021-01-14 07:43 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +use \Intaro\RetailCrm\Service\Utils as Utilyty;
Факт появления алиаса не страшен, на самом деле. А вот выбранное название вызывает смущение. Можно использовать алиас вида `RetailcrmUtils` в таком случае - сразу будет понятно, что вот этот конкретный класс к модулю относится.

2021-01-14 07:53 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/loyaltyhlblock.php
> +class LoyaltyHlBlock
С HL-блоком сервис внутри работает. Суть сервиса в том, чтобы эта деталь - тот факт, что он работает HL-блоком - была скрыта от нас при работе, и мы могли использовать сервис просто для обработки данных по ПЛ заказов.

Пример: есть JMS Serializer, в нём есть класс Serializer, внутри он работает с визитором. Класс ведь от этого не называется `VisitorDirector`, верно?

Суть названия в данном случае - отражение функционального предназначения т.к. сервисы предназначены исключительно для использования внешними компонентами.

Сервис можно назвать `OrderLoyaltyDataService`, репозиторий `OrderLoyaltyDataRepository`, а саму модель `OrderLoyaltyData`. И это будет точно отражать цель существования всех этих компонентов.

Если же в итоге окажется, что в сервисе логики обработки как таковой нет, то в дальнейшем будет логично вообще вынести оставшуюся логику сервиса в репозиторий.

2021-01-14 09:33 UTC, Neur0toxine requested changes

2021-01-14 09:33 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +use \Intaro\RetailCrm\Service\Utils as Utilyty;
@Chazovs

2021-01-14 09:33 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +
Лишний перевод строки.

2021-01-14 09:33 UTC, Neur0toxine commented on intaro.retailcrm/lib/lang/ru/service/orderloyaltydataservice.php
> +$MESS ['LP_ORDER_GROUP_NAME_EN']          = 'Loyalty program';
Лишняя строка в переводах.

2021-01-14 10:39 UTC, Neur0toxine approved these changes

2021-01-14 10:44 UTC, merged