Disabled status transfer for integration payments
retailcrm/bitrix-module pull request #179
Opened 2021-01-19 14:44 UTC by SoldierOfHeart

2021-01-26 08:28 UTC, iyzoer requested changes

2021-01-26 08:28 UTC, iyzoer commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +    public function paymentTypesGet()
есть же метод `paymentTypesList`, этот его дублирует

2021-01-26 08:28 UTC, iyzoer commented on intaro.retailcrm/classes/general/order/RetailCrmOrder_v5.php
> +        $paymentTypes = RCrmActions::apiMethod($api, 'paymentTypesGet', __METHOD__, array());
было бы все таки лучше рассмотреть хранение данных об интеграционных оплатах в настройках модуля в бд, аналогично тому, как с доставками сделано
избавимся от лишнего запроса на этапе сохранения заказа

2021-02-08 09:11 UTC, Neur0toxine requested changes

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +                    <p><small>Для интеграционных оплат, статус не передается</small></p></td>
Строка должна быть в переводах. Также здесь лишняя запятая.

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +                                    $nameType = isset($paymentType['integrationModule']) ? $APPLICATION->ConvertCharset($paymentType['name'] . '(интеграционная)', 'utf-8', SITE_CHARSET) : $APPLICATIO
Строка должна быть в переводах.

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    $deliveryIntegrationCode = array();
Нет смысла использовать старый формат объявления массива.

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    foreach ($arResult['paymentTypesList']as $typePayment) {
Между закрывающей скобкой индекса массива и оператором `as` не хватает пробела.

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    $arResult['paymentTypesList'] = $api->paymentTypesList()->paymentTypes;
Что если запрос к API не отработает как нужно?

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/order/RetailCrmOrder_v5.php
> +        $integrationPayment = unserialize(COption::GetOptionString(RetailcrmConstants::MODULE_ID, RetailcrmConstants::CRM_INTEGRATION_PAYMENT, 0));
Давно уже в коде модуля присутствует `RetailcrmConfigProvider`, в котором нужно объявить метод, возвращающий настройку, а затем использовать его.

2021-02-08 09:11 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RCrmActions.php
> +                return self::proxy($api, 'paymentTypesList', $method, array());
Этот кейс не нужен т.к. `default` его покрывает.

2021-02-15 09:40 UTC, Neur0toxine requested changes

2021-02-15 09:40 UTC, Neur0toxine commented on intaro.retailcrm/lang/en/options.php
> +$MESS ['INTEGRATION_PAYMENT_LIST'] = 'For integration payments, the status is not transferred';
С точки зрения английского языка этот перевод некорректен. Стоит помнить, что английский относится к аналитическим языкам (русский - к синтетическим). Это означает, что в английском порядок слов имеет значение. Хотя смысл этого предложения будет понятен человеку, звучать оно будет так, как если бы его написал Йода.

Предлагаю использовать нечто подобное:
`The status will not be transferred for integration payments.`

2021-02-15 09:40 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    COption::SetOptionString($mid, RetailcrmConstants::CRM_INTEGRATION_PAYMENT, serialize(RCrmActions::clearArr($integrationPayment)));
Запись тоже следует перенести в `ConfigProvider`.

2021-02-25 09:19 UTC, gwinn requested changes

2021-02-25 09:19 UTC, gwinn commented on intaro.retailcrm/classes/general/RetailcrmConfigProvider.php
> +        static::SetOption(RetailcrmConstants::CRM_INTEGRATION_PAYMENT, serialize(RCrmActions::clearArr($integrationPayment)));
@SoldierOfHeart `SetOption` же с маленькой буквы

2021-02-25 09:19 UTC, gwinn commented on intaro.retailcrm/classes/general/RetailcrmConfigProvider.php
> +        static::SetOption(RetailcrmConstants::CRM_INTEGRATION_DELIVERY, serialize(RCrmActions::clearArr($deliveryIntegrationCode)));
то же самое

2021-02-25 09:19 UTC, gwinn commented on intaro.retailcrm/classes/general/RetailcrmConstants.php
> +    const CRM_INTEGRATION_PAYMENT = 'integration_payment';
а `CRM_INTEGRATION_DELIVERY` где?

2021-02-25 09:19 UTC, gwinn commented on intaro.retailcrm/options.php
> +            $integrationPayment[$typePayment['code']] = $typePayment['code'];
А смысл хеша вида `'cash' => 'cash'`? Не проще просто массив собрать?

2021-02-25 09:19 UTC, gwinn commented on intaro.retailcrm/options.php
> +        if (isset($typePayment['integrationModule']) && $typePayment['active'] === true) {
В чем смысл закладываться на активность? Что произойдет, если потом этот тип будет активирован?

2021-02-25 09:19 UTC, gwinn commented on intaro.retailcrm/options.php
> +    $deliveryIntegrationCode = [];
В целом не понятно как в задачу по оплатам попал код ответственный за доставку

2021-02-25 11:06 UTC, SoldierOfHeart commented on intaro.retailcrm/classes/general/RetailcrmConstants.php
> +    const CRM_INTEGRATION_PAYMENT = 'integration_payment';
CRM_INTEGRATION_DELIVERY добавлена ниже была не мною 
https://github.com/retailcrm/bitrix-module/blob/master/intaro.retailcrm/classes/general/RetailcrmConstants.php#L72

2021-02-25 11:15 UTC, SoldierOfHeart commented on intaro.retailcrm/options.php
> +    $deliveryIntegrationCode = [];
при реализации задаче было обнаружено, что такая же механика по доставкам ранее была добавлена неверно (отрабатывала каждый раз при заходе в настройки, а не по событию "сохранения" настроек), поэтому в рамках задачи коснулся и доставок

2021-03-04 09:34 UTC, Neur0toxine requested changes

2021-03-04 09:34 UTC, Neur0toxine commented on intaro.retailcrm/install/step2.php
> +                            $nameType = isset($paymentType['integrationModule']) ? $APPLICATION->ConvertCharset($paymentType['name'] . GetMessage('INTEGRATIONS'), 'utf-8', SITE_CHARSET) : $APPLICATIO
Этот функционал не работает. Также стоит вывести информацию об отсутствии передачи статусов интеграционных оплат на этой странице.

2021-03-22 09:43 UTC, Neur0toxine requested changes

2021-03-22 09:43 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RetailcrmConfigProvider.php
> +    public static function getIntegrationPaymentTypes(): array
Не учтён факт того, что `RetailcrmConfigProvider::getUnserializedOption` возвращает данные такими, какими вернул их Битрикс. Там необязательно будет массив. Поэтому на чистой установке с этими изменениями ломается оформление заказов с ошибкой `Return value of RetailcrmConfigProvider::getIntegrationPaymentTypes() must be of the type array, boolean returned`.

2021-03-31 13:19 UTC, closed without merging