Lp discount order
retailcrm/bitrix-module pull request #183
Opened 2021-02-01 11:21 UTC by Chazovs

2021-02-05 07:41 UTC, Neur0toxine requested changes

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +    public function OnSaleComponentOrderResultPreparedHandler(Order $order,
Первый аргумент функции также должен быть объявлен на новой строке.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +            if (($bonusInput > 0
Нужно форматирование по PSR-12.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +
Лишний перевод строки.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +            if (isset($_POST['calculate-items-input'])
Нужно форматирование по PSR-12.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +
Лишний перевод строки.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +                $loyaltyService->applyBonusesInOrder($order,
Первый аргумент функции в вызове должен быть на новой строке при многострочном форматировании вызова.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +                || LoyaltyService::getLoyaltyPersonalStatus() !== true) {
Нужно форматирование по PSR-12.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/basket.php
> +        $calculate       = $this->service->calculateBonus($basketData['BASKET_ITEM_RENDER_DATA']);
Слишком большой отступ между переменной и равенством

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/controller/loyalty/order.php
> +            $inputBonuses);
Тут не особо понятно зачем добавлен перевод строки. Да и форматирование не соответствует PSR-12.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/orderloyaltydatarepository.php
> +        return $productsAr;
Всё содержимое блока `try` должно иметь ещё отступ по аналогии с содержимым `catch`.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/orderloyaltydatarepository.php
> +        }catch (LoaderException | SystemException | Exception $e) {
Между закрывающей фигурной скобкой тела `try` и ключевым словом `catch` должен быть пробел.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        foreach ($products as $product){
Между круглой и фигурной скобкой должен быть пробел.

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +                "LIST_FILTER_LABEL" => ['ru' => GetMessage('UF_ITEM_ID')],
А почему здесь и в других местах только `ru` локаль?

2021-02-05 07:41 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +            'en' => GetMessage('LP_ORDER_GROUP_NAME', null, 'en'),
В первом случае используется стандартная локаль. А это может быть и английская.

2021-03-16 09:11 UTC, Chazovs commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +                "LIST_FILTER_LABEL" => ['ru' => GetMessage('UF_ITEM_ID')],
добавил перевод на английский

2021-03-16 13:02 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/order_ajax.js
> +                    .replace('&#8372;', '¥')
Валюты выбраны не случайно. Значение остальных валют передаются обычным символом.
String.fromCharCode не подходит, т.к. есть euro
Значения мы берем не из раметки, а из таблицы b_catalog_currency_lang
![image](https://user-images.githubusercontent.com/45812598/111312185-1911fb00-8670-11eb-9efd-fe889997bac8.png)

Предлагаю оставить так.

2021-04-06 13:49 UTC, closed without merging