Loyalty user fields
retailcrm/bitrix-module pull request #184
Opened 2021-02-05 06:09 UTC by Chazovs

2021-02-08 09:14 UTC, Neur0toxine commented
Изначально ревью было проведено в PR https://github.com/retailcrm/bitrix-module/pull/183, от которого наследована ветка в этом PR. После закрытия дискуссий в том PR он будет закрыт, дальнейшая работа по ревью будет производиться в рамках этого PR. Причина такой запутанной и неудобной схемы организации работы в данном случае является факт зависимости этого PR от предыдущего.

2021-03-16 14:19 UTC, Neur0toxine requested changes
Очень много логики, генерирующей данные для вывода в разметку в `LoyaltyService`. Стоит подумать о том, чтобы отрефакторить её в отдельный компонент, или же (если возможно и применимо) вынести в шаблоны.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/install/export/local/components/intaro/sale.order.ajax/templates/.default/scripts/intaro.js
> +        $('#bonus-msg').html('Сколько бонусов потратить?');
Надо посмотреть в сторону переноса таких строк в переводы. Сделать это можно по аналогии с тем, как передаются товары в корзине.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +        } catch (ObjectPropertyException | ArgumentException | SystemException | \Exception $e) {
Проще сразу все `Throwable` отлавливать. Также такой отлов ошибок может затруднить поддержку.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/lang/ru/service/loyaltyservice.php
> +$MESS["RUB_BR"] = " руб.\n";
Вместо дублирования перевода с кодом `RUB` можно использовать его с добавлением переноса строки.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/orderloyaltydatarepository.php
> +            $productsAr = [];
Нейминг: тут понятно, что это массив без приписки `Ar`.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            if ($fullPrice>0) {
code quality: `$fullPrice > 0`

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            //TODO проверить передачу этого параметра (пока непонятно как)
Нужно понять как и проверить.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                {
Отформатировать согласно PSR-12.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                {
Отформатировать согласно PSR-12.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +    {
Отформатировать согласно PSR-12.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            $prices = COption::GetOptionString(Constants::MODULE_ID, Constants::CRM_PRICES, 0);
Должно быть вынесено в `ConfigProvider` и вызываться оттуда.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                $serializePrice     = unserialize($prices);
Это не понадобится если получение этой настройки будет в `ConfigProvider` вынесено.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                foreach ($basketItems as $key=>$basketItem) {
Отформатировать согласно PSR-12.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                $item['DISCOUNT_PRICE_PERCENT_FORMATED'] = $item['DISCOUNT_PRICE_PERCENT'] . '%';
Здесь отступы разъехались перед оператором присваивания. Их нужно либо убрать, либо отформатировать.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                    /(($item['FULL_PRICE']*$item['QUANTITY'])/100), 0);
Отформатировать согласно PSR-12.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +            if ($prop->getField('CODE') === 'LP_BONUS_INFO') {
Перед новым условием должен быть перевод строки.

2021-03-16 14:19 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +
Лишний перевод строки.

2021-04-05 08:26 UTC, Neur0toxine requested changes

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +
Лишняя пустая строка.

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +        }catch (Throwable $exception){
Между фигурной скобкой и `catch` должен быть пробел.

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +                            $ExtId    = null;
Стоило заменить на `camelCase`.

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/orderloyaltydatarepository.php
> +            $result = $this->dataManager::add($result);
Почему статический метод класса вызывается от его экземпляра, а не от FQN?

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        foreach ($loyaltyHls as $key=>$loyaltyHl){
Оператор `=>` в цикле должен быть обособлен пробелами.

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +     * @param                    $bonusCount /бонусная скидка в рублях
Не указан тип в аннотации.

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +     * @param                            $loyaltyDiscountInput
Не указан тип в аннотации.

2021-04-05 08:26 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        //TODO возможно, следует дописать обновление в HL блоке, а не только в самом заказе
Обновление нужно добавить.

2021-04-05 09:00 UTC, Chazovs commented on intaro.retailcrm/lib/repository/orderloyaltydatarepository.php
> +            $result = $this->dataManager::add($result);
Это связано с особенностью работы с HL блоками в Битриксе. Класс для работы с HL блоком генерируется налету, (https://i.imgur.com/d0qfmuZ.png), а дата-менеджер к нему лежит в защищенном свойстве и получается через геттер https://i.imgur.com/IY6ls5P.png

2021-04-06 13:49 UTC, closed without merging