Xml refactoring
retailcrm/bitrix-module pull request #185
Opened 2021-02-15 08:50 UTC by Chazovs

2021-03-23 11:43 UTC, Neur0toxine requested changes
В целом, достаточно странная архитектура реализована для нового генератора каталога. `IcmlDataManager` выступает как источником данных, так и их конвертером. Вдобавок, он хранит в состоянии часть данных (кэширует их), что уже делает его не просто репозиторием. Да и работает он со всеми данными сразу. В общем, это некий мультирепозиторий-конвертер на стероидах.

`IcmlWriter` отвечает только за запись данных всех типов. С ним, как раз-таки, всё в порядке.

`RetailCrmXmlBuilder` использует оба предыдущих компонента, но тоже содержит логику извлечения и конвертации данных, а также использует целую иерархию DTO для хранения своих параметров. Решение странное т.к. обычно DTO для таких целей не используются. Громоздкая и сложная конфигурация для одного класса - явный признак необходимости рефакторинга.

Также стоит заметить, что имеется факт передачи всех параметров, присутствующих в `RetailCrmXmlBuilder` в `IcmlDataManager`. Это намекает на неоправданное нарушение SRP.
 
Всё кроме `IcmlWriter` и моделей настроек компонента занимается всем понемногу. Мне было сложно разбираться в этом коде из-за смеси ответственностей в компонентах. А значит, поддерживать код будет непросто.

**А что тогда хотелось бы видеть?** Хотелось бы видеть небольшие компоненты, друг с другом не связанные. Для получения торговых предложений, товаров и так далее можно было реализовать небольшие классы репозиториев с нужными методами. Эти репозитории были бы зависимостями компонента, отвечающего за запись данных. Он бы использовать компонент `IcmlWriter`, который самостоятельно сбрасывал бы периодически кэш ICML на диск. Для инициализации всего этого использовалась бы отдельная фабрика, которая создавала бы всё, что нужно. При этом компонентам передавались бы только те параметры, которые им требуются.

Таким образом, получалась бы примерно такая иерархия зависимостей (снизу вверх).
* Репозитории для получения данных. Не содержат состояния вовсе.
* Подсистема генерации ICML.
  * `IcmlWriter`. Его параметр - лишь файл, в который ведётся запись. Сама запись ведётся путём вызовов методов для записи данных (`writeOffer` и т.д.). Метод `flush` сбрасывает кэш записи на диск.
  * Генератор каталога. Связующее звено между репозиториями и `IcmlWriter`. Главная его задача - преобразование данных в вид, требуемый `IcmlWriter`'ом, и передача их последнему.
* Фабрика, инциализирующая всё это.

Это лишь черновой пример архитектуры, и он неидеален. Например, здесь есть нарушение SOLID там, где применение оного лишь навредит нам (да, SOLID - это не набор жёстких правил, это рекомендации, нарушать их можно лишь иногда и с великой осторожностью). Однако, такая архитектура куда проще для понимания человека, который пришёл поддерживать модуль, но ранее его никогда не видел. Более глубокая проработка наверняка приведёт к изменениям в такой архитектуре (например, чтобы избежать превращения конвертера в `god class` может пригодиться рефакторинг конвертации данных в стратегии).

Следует всегда помнить, что код пишется один раз, а читается много раз. Нужно пытаться читать свой код так, будто видишь его впервые. Да, на рефакторинг уже написанного в контексте задачи кода может уйти дополнительное время. Но впоследствии код будет проще и дешевле поддерживать. Конечно, нужно не перестараться и не уйти в оверинжиниринг с постоянным рефакторингом и затягиванием задачи. Нужен баланс.

В общем, предлагаю обсудить реализацию чтобы определить куда будем двигаться дальше.

2021-03-23 12:43 UTC, Neur0toxine commented
Также реализация тестами не была покрыта.

2021-04-05 14:22 UTC, Chazovs commented on intaro.retailcrm/lib/icml/icmldatamanager.php
> +                    $xmlCategory->id       = self::MILLION + $iblock->get('ID');
решение взять из предыдущей версии. Смысл в том, что для инфоблоков (которые являются сами по себе ), у которых нет подкатегорий мы выставляем ID заведомо больший, чем возможное количество категорий в ICML.

2021-04-05 14:24 UTC, Chazovs commented on intaro.retailcrm/export/export_run.php
> +    $fileSetup->profileID = $profile_id;
Переменная прокидывается из ядра Битрикса. Поменять название нельзя.

2021-04-05 14:39 UTC, Chazovs commented on intaro.retailcrm/lib/icml/utils/icmllogger.php
> +class IcmlLogger
пока непонятно, как заменить. оставил.

2021-04-08 09:05 UTC, closed without merging