Lp 184 and 186 branches
retailcrm/bitrix-module pull request #196
Opened 2021-04-06 13:38 UTC by Chazovs

2021-04-06 15:17 UTC, Neur0toxine requested changes
В сервисы для лояльности вылезло много того, что используется в установщике.
Предлагаю этот функционал вынести в отдельный компонент, назвать его `LoyaltyInstaller`, вынести в него весь функционал, актуальный для установки, а затем использовать при установке его с инициализацией только во время установки.

Также может шокировать метод подсчёта корзины для UI. Пока что его стоит хотя бы подробнее задокументировать и слегка порефакторить с разбиением на методы.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/order/orderproduct.php
> +
Лишний перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/order/orderproduct.php
> +     * [массив] Дополнительные свойства позиции в заказе
Приписка `[массив]` тут не нужна - информация об этом в типе указана.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/order/orderproductpriceitem.php
> +}
Не хватает перевода строки в конце файла.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/order/orderproductpriceitem.php
> +namespace Intaro\RetailCrm\Model\Api\Order;
Не хватает перевода строки перед объявлением пространства имён.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/orderscreateresponse.php
> +namespace Intaro\RetailCrm\Model\Api\Response;
Не хватает перевода строки перед объявлением пространства имён.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/orderscreateresponse.php
> +/**
Между докблоком и сигнатурой начала файла должен быть перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/orderseditresponse.php
> +namespace Intaro\RetailCrm\Model\Api\Response;
Не хватает перевода строки перед объявлением пространства имён.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/orderseditresponse.php
> +/**
Между докблоком и сигнатурой начала файла должен быть перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/api/response/orderseditresponse.php
> +}
Не хватает перевода строки в конце файла.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +     * @param                                                                              $rate /курс бонуса к валюте
Тип не указан.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                ->fetch();
Выглядит как код, который должен находиться в репозитории.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                );
Неверно отформатирован многострочный вызов.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        //TODO возможно, следует дописать обновление в HL блоке, а не только в самом заказе
Уже нет. Обновлять нужно лишь то, что нужно для обмена. Всё лишнее нужно удалить как из HL-блока, так и из обработки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                    ->fetch();
Выглядит как код для выноса в репозиторий.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        if ((int)$loyaltyDiscountInput === 0) {
Между приведением к типу и переменной должен быть перевод строки.
В данном случае приведение не нужно - достаточно нестрогой проверки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                        . "; \n";
Может, вынести это в отдельный метод?

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $customerId = (string)$userId;
Было хорошо, стало плохо. Надо вернуть как было.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +
Лишний перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +
Лишний перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +            $LPGroup = OrderPropsGroupTable::query()
Нейминг: здесь некая мутация из Go. Мы используем `camelCase` - нужно использовать его и здесь.
Например, `$lpGroup`.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
>          $arCartFields = [
Нужно подумать что сделать с этим длинным массивом. Сейчас очень страшно получилось.
Возможно, стоит вынести в отдельный метод его формирование с документированием метода.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +                }else {
Перед `else` нужен перевод строки.

2021-04-06 15:17 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +                }else {
Перед `else` нужен перевод строки.

2021-04-07 06:27 UTC, Chazovs commented on intaro.retailcrm/classes/general/events/RetailCrmEvent.php
> +    protected static $CRM_PAYMENT            = 'payment_arr'; //order payment Y/N
удалил в 6 местах.

2021-04-07 07:15 UTC, Chazovs commented on intaro.retailcrm/install/export/local/components/intaro/lp.score/component.php
> +        $arResult['NEXT_LEVEL_SUM']          = (int)$response->nextLevelSum === 0 ? '-' : $response->nextLevelSum;
исправил везде по коду

2021-04-07 07:17 UTC, Chazovs commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +            $loyaltyDiscountInput = (float)$request->get('loyalty-discount-input');
исправил везде по коду

2021-04-07 07:19 UTC, Chazovs commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +                        $item['data']['SUM']     = $item ['data']['SUM_NUM'] . GetMessage('RUB');
ПЛ только с рублями работает.

2021-04-07 07:20 UTC, Chazovs commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +                                                        = $jsDataTotal['ORDER_PRICE'] - $loyaltyDiscountInput . ' ' . GetMessage('RUB');
см предыдущий

2021-04-07 07:20 UTC, Chazovs commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +                && (int)$_POST['available-bonuses'] >= (int)$_POST['bonus-input'];
исправил везде по коду

2021-04-07 07:58 UTC, Chazovs commented on intaro.retailcrm/lib/model/api/order/createorder.php
> +class CreateOrder extends Order
для соответствиня названий объектов. Запрос на создание заказа возвращает CreateOrder
![image](https://user-images.githubusercontent.com/45812598/113831206-07fc6b80-9790-11eb-8e46-9554148c5bea.png), а запрос на обновление возвращает просто Order 
![image](https://user-images.githubusercontent.com/45812598/113831342-2bbfb180-9790-11eb-9e79-50e7c371e224.png)

2021-04-07 08:13 UTC, Chazovs commented on intaro.retailcrm/lib/model/api/order/orderproduct.php
> +/**
исправил везде по коду

2021-04-07 08:28 UTC, Chazovs commented on intaro.retailcrm/lib/model/api/response/orderscreateresponse.php
> +namespace Intaro\RetailCrm\Model\Api\Response;
исправил везде по коду

2021-04-07 08:32 UTC, Chazovs commented on intaro.retailcrm/lib/model/api/response/orderscreateresponse.php
> +/**
исправил везде по коду

2021-04-07 08:50 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        //TODO возможно, следует дописать обновление в HL блоке, а не только в самом заказе
этот метод может оказаться невостребованным в ближайшее время. Правки по нему предлагаю пока не вносить.

2021-04-07 08:55 UTC, Chazovs commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +        $customerId = (string)$userId;
сделал хорошо везде по коду

2021-04-08 10:31 UTC, Neur0toxine requested changes

2021-04-08 10:31 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/loyaltyservice.php
> +                        . "; \n";
@Chazovs

2021-04-08 10:31 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +    private function getGroupID($personId): ?int
Нейминг некорректен. Должен быть `camelCase`.

2021-04-08 10:31 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +            $lPGroup = OrderPropsGroupTable::query()
Нейминг некорректен. Должен быть `camelCase`.

2021-04-08 10:31 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/orderloyaltydataservice.php
> +            $groupID  = $this->getGroupID($personId);
Нейминг некорректен. Должен быть `camelCase`.

2021-04-15 11:03 UTC, Chazovs commented on intaro.retailcrm/lib/component/handlers/eventshandlers.php
> +        if (self::$disableSaleHandler === true) {
строгая проверка страхует нас от того, что публичному статическому свойству этого класса будет присвоено по ошибке не булевое значение. Не стоит сокращать эту проверку.

2021-04-19 12:44 UTC, merged