Make repositories
retailcrm/bitrix-module pull request #197
Opened 2021-04-08 09:00 UTC by Chazovs

2021-04-08 13:49 UTC, Neur0toxine requested changes
В целом, результат намного лучше предыдущего. Но билдерам делегировано слишком много функционала. Нужны архитектурные исправления, а также исправления качества кода.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/icmldirector.php
> +        $this->setXmlData();
Компонент при инициализации часть данных вытягивает. Это плохо. Конструктор предназначен для того, чтобы инициализировать все нужные компоненту зависимости (присвоить прокинутое через DI, вытянуть из локатора, создать то, что имеет смысл создавать здесь).

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +    }
Стоит убрать этот фрагмент.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlofferbuilder.php
> +            $offerParam->name  = GetMessage("PARAM_NAME_$code");
Лучше использовать обычную конкатенацию - улучшит читаемость.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlofferbuilder.php
> +            if (empty(GetMessage("PARAM_NAME_$code"))) {
Это сообщение дважды извлекается - можно поместить его сначала в переменную.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlofferbuilder.php
> +        $this->catalogRepository = new CatalogRepository();
Билдеры напрямую с источником данных не должны работать. В них передаются конкретные данные, а затем они выдают результат.

Как раз извлечением данных и работой с билдером директор должен заниматься.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlcategoriesbuilder.php
> +        $this->fileRepository    = new FileRepository($this->setup->defaultServerName);
Аналогично предыдущему: билдер напрямую с источниками данных не работает.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +        if ($writingOffers + count($xmlOffers) > $maxOffersValue) {
Здесь для улучшения читаемости лучше первый предикат обернуть в скобки.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/xml/unit.php
> +    public function mergeWithOtherUnit(?Unit $unitCode): Unit
Достаточно и просто `merge`.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/xml/xmlcategory.php
> +    public $id;
Некорректное форматирование.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/xml/xmldata.php
> +
Лишний перевод строки.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/xml/xmlsetup.php
> +
Лишний перевод строки.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/model/bitrix/xml/xmlsetup.php
> +
Лишний перевод строки.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/filerepository.php
> +        if ((bool)preg_match($validation, $pathImage) === false) {
Тут нужен пробел между кастом и вызовом функции.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hl.php
> +
Лишний перевод строки.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writer = $writer = new XMLWriter();
Не надо так делать. Лучше сначала записать значение во `$writer`, настроить `$writer`, а затем записать его в свойство. Или же записать напрямую в свойство и напрямую из свойства вызывать методы класса.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writeSimpleAttribute('date', Date('Y-m-d H:i:s'));
Это лучше вынести в метод. Можно вынести вместе с инициализацией.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writer->endElement();
При каких условиях этот код будет работать? Выглядит как потенциальная точка отказа.

2021-04-08 13:49 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlcategoriesbuilder.php
> +    private const MILLION     = 1000000;
Почему именно такая константа была выбрана? Также здесь отступ некорректный.

2021-04-08 13:49 UTC, Neur0toxine commented
@Chazovs поправь конфликты, пожалуйста.

2021-04-08 14:16 UTC, Chazovs commented on intaro.retailcrm/lib/icml/querybuilder.php
> +class QueryBuilder
переименовал в QueryParamsMolder, чтобы не было ассоциации с паттерном.

2021-04-08 14:29 UTC, Chazovs commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writeSimpleAttribute('date', Date('Y-m-d H:i:s'));
Можно пояснить причину?

2021-04-08 14:31 UTC, Chazovs commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writer->endElement();
этот код закрывает открытые в начале записи теги. метод запускается директором в generateXml()

2021-04-08 14:34 UTC, Chazovs commented on intaro.retailcrm/lib/icml/xmlcategoriesbuilder.php
> +    private const MILLION     = 1000000;
Причины появления объяснял в прошлом ревью. Смысл в том, что некоторые товары могу располагаться не в категориях, а в корне инфоблока. тогда сам инфоблок нужно записать как категорию. для этого ему нужно присвоить такой айди, который заведомо не будет пересекаться с айди ни одной категории.

2021-04-08 15:01 UTC, Chazovs commented on intaro.retailcrm/export/export_run.php
> +    $fileSetup->properties->products = new XmlSetupProps();
сделал для XmlSetupProps и для XmlSetupPropsCategories. 
для XmlSetup не получится - слишком много параметров

2021-04-08 15:11 UTC, Chazovs commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writeSimpleAttribute('date', Date('Y-m-d H:i:s'));
зачем выносить это в отдельный метод?

2021-04-09 07:39 UTC, Chazovs commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
Эти методы никак не относятся к построению объектов.  Они не устанавливают его свойств, не создают экземпляров. Они по сути перебирают массивы. Не думаю, что их следует выносить в билдеры.

2021-04-12 08:06 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writeSimpleAttribute('date', Date('Y-m-d H:i:s'));
Чтобы вынести код инициализации нижележащего `XMLWriter` из конструктора. Назвать метод можно `initXmlWriter` например.

2021-04-12 08:07 UTC, Neur0toxine commented on intaro.retailcrm/export/export_run.php
> +    $fileSetup->properties->products = new XmlSetupProps();
> для XmlSetup не получится 
В нём просто в конструкторе нужно было создавать `XmlSetupPropsCategories` и присваивать полученное в `properties`. А уже в конструкторе `XmlSetupPropsCategories` должны создаваться `XmlSetupProps` для обоих свойств экземпляра класса.

2021-04-12 08:15 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
Хорошим тоном считается слабое сцепление модулей и высокая связность внутри модулей (это часть [GRASP](https://en.wikipedia.org/wiki/GRASP_(object-oriented_design))). Любой модуль может содержать свою внутреннюю реализацию, которая предназначена только для использования самим модулем - и ни для чего больше. Для этого и был придуман модификатор `private`.

Подавляющее большинство статических методов класса `IcmlUtils` вызываются только в `XmlOfferBuilder`. Почему бы их не поместить туда? Они ведь являются внутренней реализацией `XmlOfferBuilder`. Вынос этих методов из `XmlOfferBuilder` в `IcmlUtils`  снизил связность и усилил сцепление, причём абсолютно неоправданно.

Вполне вероятно, что вынос методов обратно в `XmlOfferBuilder` покажет необходимость в рефакторинге `XmlOfferBuilder`, что трудно заметить сейчас. Это ещё один аргумент против текущей архитектуры.

2021-04-12 08:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/querybuilder.php
> +class QueryBuilder
А почему не называть фабрикой этот компонент? Он же и является фабрикой, пусть и не очень аккуратной (разные запросы создаёт).

Предлагаю всё же назвать компонент фабрикой.

2021-04-12 08:21 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/icmlwriter.php
> +        $this->writer->endElement();
Вполне логично выше этого метода добавить тот, который в начале записи теги открывает (относится к другому замечанию с выносом открытия тегов из конструктора). Вероятно, стоит и из конструктора запись тегов убрать, делегируя вызов записи первичных тегов директору.

2021-04-12 08:30 UTC, Chazovs commented on intaro.retailcrm/export/export_run.php
> +    $fileSetup->properties->products = new XmlSetupProps();
я же так и сделал. Просто  у XmlSetup кроме properties еще куча свойств

2021-04-12 09:08 UTC, Chazovs commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
Как тогда быть с тем, что методы, которые очищают массивы или  преобразуют габариты в нужные единицы измерения, попав в XmlOfferBuilder, нарушат принцип единой ответственности, ведь XmlOfferBuilder отвечает сейчас только за сборку объекта XmlOffer?

2021-04-12 09:24 UTC, Chazovs commented on intaro.retailcrm/lib/icml/querybuilder.php
> +class QueryBuilder
Тогда что делать с методом getWhereForOfferPart? он собирает ассоциативные массивы. При чем тут фабрика?

2021-04-12 11:31 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
А разве методы обработки данных в билдере не являются его внутренней реализацией? Я ведь писал, что
> Подавляющее большинство статических методов класса `IcmlUtils` вызываются только в `XmlOfferBuilder`
Это значит, что ты внутреннюю реализацию вынес в отдельный класс. Это лишнее усложнение.

SRP, как и другие принципы проектирования нельзя применять без анализа задачи. Любая задача иерархична т.е. содержит в себе подзадачи. Архитектурно мы скрываем мелкие подзадачи большей задачи за интерфейсом, чтобы, например, другие компоненты системы могли не думать о том, как им данные фильтровать, куда писать их, а могли просто вызвать компонент, который решает более общую задачу - генерацию каталога. В итоге проектируемую систему проще всего представить в виде слоистой модели, где внутренние слои выполняют более простые задачи (например, просто запись в файл XML-тегов с данными), а внешние слои выполняют более сложные, более *абстрактные* задачи.

Например, у нас есть нижний слой, который занимается конвертацией веса товара из различных единиц в килограммы. Это очень простая задача, реализуемая небольшим количеством кода. Её применить можно во многих местах. Если нам она нужна лишь в одном компоненте, то имеет смысл вынести эту задачу в метод компонента. Если же она нужна во многих местах, то стоит подумать о сервисе. Если впоследствии окажется, что задача стала слишком сложной и метод раздулся, то её стоит отрефакторить в компонент.

Другой пример - у нас есть слой более высокого уровня, который занимается генерацией данных торгового предложения. Эта задача требует намного больше логики, нежели предыдущая. В зависимости от данных и требуемой логики может оказаться, что один из общепринятых паттернов нам подходит. Например, нам может подойти паттерн *Строитель* (*Builder*), который изначально и был придуман для больших и сложных объектов. Сам билдер - это просто большой конструктор, вынесенный в отдельный компонент т.к. в нём много сложной логики. Почему мы не храним эту логику в конструкторе? Потому что получится огромный метод минимум на 300-400 строк, который поддерживать будет как минимум затруднительно.

Дискуссия возникла как раз вокруг вот этих двух задач. Теперь возьмём эти две задачи и посмотрим хорошенько на них. В данном случае конвертация веса нам нужна только лишь для того, чтобы записать в `<weight />` корректное значение веса. А зачем нам нужно туда его записывать? Затем, что запись веса товара в тег - это подзадача задачи записи данных товара в каталог, а задача записи товара в каталог - это подзадача задачи генерации каталога. Т.е. конвертация веса здесь - это подзадача для задачи `XmlOfferBuilder`.

Конвертация веса не требует большого количества кода (реализация в PR - 23 строки кода). Она не используется нигде кроме генератора оффера. А значит, логично и правильно вынести конвертацию веса в метод `XmlOfferBuilder`.

Проектируя систему всегда нужно исходить из требований к ней. Это надёжность, применимость, расширяемость, поддерживаемость - и так далее. Саму архитектуру мы делаем прежде всего для тех, кто будет систему поддерживать. Потому что компьютеру в общем-то всё равно какой код исполнять и в каком порядке (ну, не совсем всё равно, но это уже к другой теме относится). Процессор не выскочит из сокета и не убежит если его заставят выполнять код опенкарта например, потому что ему опенкарт не нравится. А вот человек вряд ли сможет поддерживать работу плохо спроектированной системы с кодом низкого качества так, чтобы она соответствовала всем представленным к ней требованиям, в т.ч. чтобы стоимость поддержки не уходила в бесконечность.

Ну и, конечно, не стоит забывать о классическом правиле:
> Пишите код так, как будто поддерживать его будет склонный к насилию психопат, который знает, где вы живёте.

2021-04-12 11:34 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/querybuilder.php
> +class QueryBuilder
Посмотреть как он используется и можно ли вынести сборку в целом запроса сюда.
Если же эти массивы только для запроса и используются, то без проблем можно прямо здесь его и оставить.

2021-04-12 12:01 UTC, Chazovs commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
Я понял твою мысль так: пока метод используется лишь в одном классе, то выносить его в отдельный класс преждевременно. Но если подумать об этом так: по каким причинам нам может понадобиться вносить изменения в XmlOfferBuilder? Очевидно, что сейчас такой причиной может быть лишь изменение собираемого объекта (например у него появятся или удалятся некоторые поля). Когда же мы добавим туда метод, который будет пересчитывать габариты, то причин для изменения будет уже две. Этим мы привяжем наш билдер к требованиям icml. Сейчас вес габариты указываются как длина/ширина/высота. А завтра формат изменится и мы пойдем менять его в билдер.

2021-04-12 12:08 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
Для чего нужен `XmlOfferBuilder`? Для того, чтобы собирать данные, которые можно сразу же дописать в ICML-каталог в директоре. И всё, он больше нигде не нужен. Не надо билдер отрывать от основной задачи; он решает её подзадачу. Пытаясь абстрагироваться от этого ты неоправданно усложнишь архитектуру, а пользы от этого не будет т.к. публичным интерфейсом получившейся подсистемы был и остаётся директор.

2021-04-12 12:12 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
>  пока метод используется лишь в одном классе, то выносить его в отдельный класс преждевременно

Мы говорим сейчас не только в контексте методов / классов, а также учитывая то, что компоненты между собой как-то взаимодействуют, они решают какие-то свои подзадачи. На это нужно обращать внимание при проектировании, а ты эту часть сейчас игнорируешь, и пытаешься строить академически правильную, но неприменимую на практике архитектуру.

2021-04-12 12:19 UTC, Neur0toxine commented on intaro.retailcrm/export/export_run.php
> +    $fileSetup->properties->products = new XmlSetupProps();
Если эти свойства не пустые DTO, то пусть остаются как есть, они должны заполняться клиентским кодом.

2021-04-12 12:35 UTC, Chazovs commented on intaro.retailcrm/lib/icml/utils/icmlutils.php
> +class IcmlUtils
Не вижу смысла продолжать спор. Сделал, как ты хочешь, остался при своем мнении)

2021-04-12 12:56 UTC, Chazovs commented on intaro.retailcrm/lib/icml/querybuilder.php
> +class QueryBuilder
он используется как массив дальше.  Предлагаю не переименовывать.

2021-04-13 14:19 UTC, Neur0toxine requested changes

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlofferbuilder.php
> +    public function createXmlOffer(): XmlOffer
Идея билдера в том, что он позволяет сначала задать множество входных параметров для формирования объекта, а затем сформировать объект одним вызовом. Выглядеть это должно как-то так:

```php
$builder = new Builder();
$builder
    ->setFirst(...)
    ->setSecond(...)
    ->setThird(...)
    ->setFourth(...);

try {
    $result = $builder->build();
} catch (BuilderException $exception) {
    // здесь обрабатываем ошибку сборки билдером результата
}
```

Типовая внутренняя реализация билдера при этом состоит из следующих компонентов:
- Свойства, храняющие исходные данные.
- Сеттеры, заполняющие свойства.
- Логика сборки объекта (может быть в одном методе, или в нескольких).

Внутрненнюю логику необязательно менять под такой вид. А вот внешний интерфейс лучше привести к единому виду (сеттеры + метод `build`).

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlcategoryfactory.php
> +class XmlCategoryFactory
Как и в случае с `XmlOfferFactory`, это скорее директор, нежели фабрика.
Нужно просто переименовать компонент.

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlcategoryfactory.php
> +
Лишний перевод строки.

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/xmlcategoriesbuilder.php
> +}
Компонент маловат чтобы билдером быть. Тут просто фабричный метод.
Предлагаю сам компонент назвать `XmlCategoryFactory`, а метод назвать просто `create`, при этом сделав его статическим.

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/siterepository.php
> +}
Не хватает перевода строки в конце файла.

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hl.php
> +class Hl {
Открывающая скобка тела класса должна быть на новой строке.

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hl.php
> +     * @param $HlBlockId
Не указан тип переменной в аннотации.

2021-04-13 14:19 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/hl.php
> +     * @param $name
Не указан тип переменной в аннотации.

2021-04-19 12:43 UTC, merged