Multsite for order type
retailcrm/bitrix-module pull request #202
Opened 2021-04-30 15:06 UTC by RenCurs

2021-05-24 06:42 UTC, Neur0toxine commented
На вкладке "Общие настройки" в секции "Активные сайты" маппинг магазинов на сайты не сохраняется.

2021-05-24 06:42 UTC, Neur0toxine requested changes

2021-05-24 06:42 UTC, Neur0toxine commented on intaro.retailcrm/update/updater-5.5.0.php
> -}
Этот апдейтер не нужно было обновлять. В модуле предусмотрена своя система апдейтеров.

2021-05-24 06:42 UTC, Neur0toxine commented on intaro.retailcrm/update/updater-5.6.3.php
> +    }
Лишняя проверка наличия `COption`. Используется ведь `Bitrix\Main\Config\Option` из D7.

2021-05-24 08:07 UTC, RenCurs commented on intaro.retailcrm/update/updater-5.5.0.php
> -}
То есть файл не нужно было удалять?

2021-05-26 12:21 UTC, Neur0toxine requested changes

2021-05-26 12:21 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RCrmActions.php
> +            $personTypes = \Bitrix\Sale\PersonType::load($site['LID']);
Нужно заменить на импорт.

2021-05-26 12:21 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RCrmActions.php
> +    public static function getOrderTypesListSite($arSites)
Необходимость передачи массива именно данных сайтов выглядит избыточной. Более правильно было бы передавать обычный список идентификаторов сайтов.

2021-05-26 12:21 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +                    $contragentTypes = array_flip($contragentTypes[$site]);
Маппинга типов плательщиков для текущего сайта может и не быть. Нужно проверять его наличие перед извлечением данных.

2021-05-26 12:21 UTC, Neur0toxine commented on intaro.retailcrm/lang/en/options.php
> +$MESS['COUNTERPATY_SETTINGS'] = "Counterparty matches must be configured 1 to 1 for";
Здесь более корректно использовать сообщение вида:
```
Counterparty mapping for the %key% must be configured in one-to-one order
```
где `%key%` - место подстановки параметра `key`. Инструкция по использованию подстановок находится [здесь](https://dev.1c-bitrix.ru/api_help/main/functions/localization/getmessage.php).

2021-05-26 12:22 UTC, Neur0toxine commented
Также вижу множество изменений, которые представляют из себя замену отступов. Вероятно, это сделала IDE автоматически. Лучше предотвращать попадание в PR / MR таких изменений т.к. это усложняет и замедляет процесс ревью.

2021-05-28 06:29 UTC, Neur0toxine requested changes

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            }, $arResult['arSites'] ?? []);
`array_column` здесь будет быстрее.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            }, $arResult['arSites'] ?? []);
Также `array_column`.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/install/index.php
> +            }, RCrmActions::SitesList() ?? []);
Также `array_column`. Одинаковые обработки нужно вынести в отдельный метод чтобы не дублировать код.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/install/step11.php
> +    echo CAdminMessage::ShowMessage(GetMessage($arResult['errCode']));
Нужно по PSR оформить.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/install/step2.php
> +}, $arResult['arSites'] ?? []);
В этом месте также дублируется обработка.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/install/step3.php
> +}, $arResult['arSites'] ?? []);
И здесь дублируется.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    }, $arResult['arSites'] ?? []);
Дублируется обработка, нужен `array_column` вместо `array_map`.

2021-05-28 06:29 UTC, Neur0toxine commented on intaro.retailcrm/options.php
> +    }, $arResult['arSites'] ?? []);
Дублируется обработка, нужен `array_column` вместо `array_map`.

2021-05-31 08:11 UTC, closed without merging