sync managers
retailcrm/bitrix-module pull request #206
Opened 2021-06-02 15:13 UTC by Chazovs

2021-06-11 14:22 UTC, Neur0toxine requested changes

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RCrmActions.php
> +        $service->synchronizeManagers();
Сервис должен в сервис-локаторе быть. Но пока лучше использовать синглтон.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/events/RetailCrmEvent.php
> +            $managerService = new ManagerService();
Аналогично предыдущему.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +            require_once dirname(__FILE__) . '/RetailUser.php';
Пока ведь `include.php` используется для этих целей.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +                //TODO функция отсутствует в модуле. Возможно условие стоит удалить.
Это условие для кастомов предназначено. Пользователь объявляет такую функцию и вносит изменения в объект заказа в ней. Модуль в момент загрузки истории обнаруживает функцию и вызывает её.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +                        //TODO заменить вызов на сервис-локатор, когда он приедет
В таком случае было бы правильнее временно сделать синглтоном `ManagerService` и вызывать так:
```php
ManagerService::getInstance()
```

А уже методу `getService` указать тег `@todo` с этим текстом.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailCrmHistory_v5.php
> +                        //TODO заменить вызов на сервис-локатор, когда он приедет
Аналогично предыдущему.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/history/RetailUser.php
> +class RetailUser extends CUser
Не очень хорошо в global namespace этот класс объявлять.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/order/RetailCrmOrder_v5.php
> +                $managerService = new ManagerService();
Заменить на синглтон.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/lib/lang/ru/repository/managerrepository.php
> +$MESS['REP_ERR'] = 'Ошибка репозитория в методе ';
Лучше для локализации ошибки использовать подстановку в шаблоне сообщения об ошибке: https://dev.1c-bitrix.ru/api_help/main/functions/localization/getmessage.php
Также стоит использовать аналог из D7: https://dev.1c-bitrix.ru/api_d7/bitrix/main/localization/loc/getmessage.php

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/managerrepository.php
> +            $this->logger->write(GetMessage('REP_ERR') . __METHOD__, 'repositoryErrors');
Здесь нужно подстановку использовать.

2021-06-11 14:22 UTC, Neur0toxine commented on intaro.retailcrm/lib/service/managerservice.php
> +    }
Этот метод вызывается в одном месте. Вероятно, не стоит переносить в него один вызов из другого класса.

2021-06-21 08:05 UTC, Chazovs commented on intaro.retailcrm/classes/general/history/RetailUser.php
> +class RetailUser extends CUser
Все классы истории (classes/history) требуют выноса из глобального нэймспейса. Думаю, лучше будет вынести их все вместе, скоординировано, когда эти классы будут рефакториться.

2021-07-06 09:26 UTC, Neur0toxine requested changes

2021-07-06 09:26 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/order/RetailCrmOrder_v5.php
> +    public static function uploadOrders($pSize = 50, $failed = false, array $orderList = null)
Мы ведь используем пустой массив в качестве пустого значения типа `array`.

2021-07-06 09:26 UTC, Neur0toxine commented on intaro.retailcrm/include.php
> +use Bitrix\Main\Context;
Этот файлик в принципе не стоило трогать. В версии модуля с ПЛ он совсем другой.

2021-07-06 09:26 UTC, Neur0toxine commented on intaro.retailcrm/lib/repository/managerrepository.php
> +            $this->logger->write(GetMessage('REP_ERR', ['#METHOD#' => __METHOD__]), 'repositoryErrors');
Странно, что такие ошибки не передаются caller'у, а просто пишутся в лог.

2021-08-19 10:32 UTC, Neur0toxine approved these changes

2021-08-19 12:46 UTC, merged