icml simple product props protected
retailcrm/bitrix-module pull request #207
Opened 2021-06-03 13:45 UTC by Chazovs

2021-06-15 09:56 UTC, Neur0toxine requested changes

2021-06-15 09:56 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RetailcrmConfigProvider.php
> +        );
Тут лучше использовать `static::getOption`.

2021-06-15 09:56 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/RetailcrmConfigProvider.php
> +        );
А здесь `static::setOption`.

2021-06-15 09:56 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/settingsservice.php
> +     * @param        $field
Не указан тип в аннотации.

2021-06-15 09:56 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/settingsservice.php
> +     * @param            $unitTypeName
Не указаны типы в аннотации.

2021-06-15 09:56 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/settingsservice.php
> +     * @return array|null
Для массивов стоит возвращать пустой массив в качестве пустого элемента.

2021-06-15 09:56 UTC, Neur0toxine commented on intaro.retailcrm/lib/icml/settingsservice.php
> +     */
Здесь стоит дополнительно указать в summary что именно делает этот метод.

2021-07-08 12:20 UTC, Chazovs commented on intaro.retailcrm/install/index.php
> +            $strVars .= 'iblockExport[' . $key . ']=' . $val . '&';
не вижу такой возможности, потому что нам нужно изменять ключ массива. упростил путем инкапсуляции повторяющихся участков кода

2021-09-06 11:44 UTC, Neur0toxine commented
Всё ещё сохраняется ошибка с невозможностью генерации каталога при обновлении с предыдущей версии модуля (в качестве предыдущей версии используется актуальный срез `master`):

```
Array
(
    [TIME] => 2021-09-06 14:41:56
    [DATA] => Не выбрано ни одного инфоблока для экспорта
)
```

2021-09-07 11:05 UTC, Chazovs commented
> Всё ещё сохраняется ошибка с невозможностью генерации каталога при обновлении с предыдущей версии модуля (в качестве предыдущей версии используется актуальный срез `master`):
> 
> ```
> Array
> (
>     [TIME] => 2021-09-06 14:41:56
>     [DATA] => Не выбрано ни одного инфоблока для экспорта
> )
> ```
Добавил апдейтер, который проводит нужные изменения. Проверил в командной строке - работает.

2021-09-08 07:05 UTC, merged