Corp uploading fix
retailcrm/bitrix-module pull request #210
Opened 2021-07-02 08:59 UTC by Chazovs

2021-07-06 09:01 UTC, Neur0toxine requested changes

2021-07-06 09:01 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/user/RetailCrmUser.php
> +        if ( mb_strlen($arFields['EMAIL']) < 100) {
Лишний пробел.

2021-07-06 09:01 UTC, Neur0toxine commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +        unset($params['urlId']);
Стоит подумать как без костыля передавать эти данные.

2021-07-08 10:03 UTC, Chazovs commented on intaro.retailcrm/classes/general/ApiClient_v5.php
> +        unset($params['urlId']);
Можно добавить в RCrmActions::apiMethod параметр и в proxy соответственно. Но это не лучшая реализация. Я бы предложил убрать этот костыль после появления ПЛки

2021-07-08 13:28 UTC, Neur0toxine approved these changes

2021-07-08 13:29 UTC, merged